import {rpc,demoEnabled,createPaymentSession,createRefund,createPayout} from '@catera/backend';
import type {Checkout} from '@catera/domain';
export const maxDuration=300;
const system=<T=unknown>(action:string,payload:unknown={})=>rpc<T>(null,null,'catera_v1_system',{action,payload},true);
const pushHeaders=()=>({'Content-Type':'application/json',...(process.env.EXPO_ACCESS_TOKEN?{Authorization:'Bearer '+process.env.EXPO_ACCESS_TOKEN}:{})});
export async function GET(request:Request){if(!process.env.CRON_SECRET||request.headers.get('authorization')!=='Bearer '+process.env.CRON_SECRET)return new Response('Unauthorized',{status:401});await system('maintenance');const jobs=await system<{id:string;kind:string;payload:Record<string,string>}[]>('outbox.claim');let done=0;
 for(const job of jobs){try{
  if(job.kind==='payment.create'){if(!demoEnabled()){const c=await system<Checkout>('payment.lookup',{id:job.payload.checkoutId});if(c.state==='pending'&&!c.payment_url){const data=await createPaymentSession(c);await system('payment.attach',{id:c.id,...data});}}}
  else if(job.kind==='refund.create'){const r=await system<{id:string;amount:number;state:string;payment:{provider_id:string}}>('refund.lookup',{id:job.payload.refundId});if(r.state==='requested'){const data=demoEnabled()?{id:'demo-'+r.id,status:'SUCCEEDED'}:await createRefund(r);await system('refund.update',{id:r.id,providerId:data.id,state:data.status==='SUCCEEDED'?'succeeded':data.status==='FAILED'?'failed':'pending'});}}
  else if(job.kind==='payout.create'){const p=await system<{id:string;amount:number;caterer_id:string;status:string}>('payout.lookup',{id:job.payload.payoutId});if(p.status==='approved'){const data=demoEnabled()?{payout_id:'demo-'+p.id,status:'ACCEPTED'}:await createPayout(p);await system('payout.update',{id:p.id,providerId:data.payout_id,status:'pending'});}}
  else if(job.kind==='push'){const tokens=await system<string[]>('devices',{userId:job.payload.userId});for(let offset=0;offset<tokens.length;offset+=100){const batch=tokens.slice(offset,offset+100);const response=await fetch('https://exp.host/--/api/v2/push/send',{method:'POST',headers:pushHeaders(),body:JSON.stringify(batch.map(to=>({to,title:'Catera',body:job.payload.body,collapseId:job.id,data:{href:job.payload.href,notificationId:job.id}}))),signal:AbortSignal.timeout(15000)});if(!response.ok)throw new Error('PUSH_SEND_FAILED');const result=await response.json();for(const[i,ticket]of (result.data||[]).entries()){if(ticket.status==='ok')await system('push.ticket',{id:ticket.id,jobId:job.id,token:batch[i]});else if(ticket.details?.error==='DeviceNotRegistered')await system('device.remove',{token:batch[i]});else throw new Error('PUSH_TICKET_FAILED');}}}
  else if(job.kind==='split.reconcile')continue; // Remains visible until an explicit admin reconciliation.
  await system('outbox.complete',{id:job.id});done++;
 }catch(error){await system('outbox.retry',{id:job.id,error:error instanceof Error?error.message:'JOB_FAILED'});}}
 const tickets=await system<{id:string;token:string}[]>('push.receipts');if(tickets.length){const response=await fetch('https://exp.host/--/api/v2/push/getReceipts',{method:'POST',headers:pushHeaders(),body:JSON.stringify({ids:tickets.map(t=>t.id)}),signal:AbortSignal.timeout(15000)});if(response.ok){const result=await response.json();for(const [id,receipt]of Object.entries(result.data||{})){const r=receipt as {status:string;details?:{error:string}};await system('push.checked',{id,remove:r.details?.error==='DeviceNotRegistered'});}}}
 return Response.json({processed:done,health:await system('health')});}
