import { test, expect } from "@playwright/test";
import AxeBuilder from "@axe-core/playwright";
for (const locale of ["id","en"]) test(`delivery issue -> seller attention -> resolution -> customer escalation ${locale}`, async({page,baseURL})=>{
 await page.context().addCookies([{name:"catera_locale",value:locale,url:baseURL!}]);
 await page.setViewportSize({width:390,height:950});
 await page.request.post("/api/v1/auth/demo",{data:{role:"customer"}});
 const customer=(await (await page.request.get("/api/v1/customer")).json()).data;
 const deliveries=customer.deliveries.filter((d:any)=>d.offer.catererId==="10000000-0000-4000-8000-000000000001");
 const d=deliveries[locale==="id"?0:1];
 await page.goto("/deliveries/"+d.id);
 await page.getByRole("link",{name:/Laporkan masalah|Report an issue/}).click();
 const dialog=page.getByRole("dialog");
 await expect(dialog).toContainText(d.service_date);
 await dialog.getByRole("textbox").fill("Synthetic delivery issue "+locale);
 await dialog.getByRole("button",{name:/Kirim laporan|Send report/}).click();
 await expect(dialog).toHaveCount(0);
 await expect(page.getByRole("region",{name:/Kendala pengantaran|Delivery issues/})).toContainText("Synthetic delivery issue "+locale);
 const issues=(await (await page.request.get("/api/v1/delivery-issues")).json()).data;
 const issue=issues.find((i:any)=>i.day_id===d.id);
 await page.request.post("/api/v1/auth/demo",{data:{role:"owner"}});
 await page.goto("/seller");
 const attention=page.getByRole("region",{name:/Perlu perhatian|Needs attention/});
 await expect(attention.locator(`a[href="/seller/support?issue=${issue.id}"]`)).toBeVisible();
 await attention.locator(`a[href="/seller/support?issue=${issue.id}"]`).click();
 const region=page.getByRole("region",{name:/Kendala pengantaran|Delivery issues/});
 await expect(region).toContainText("Synthetic delivery issue "+locale);
 await region.getByRole("combobox",{name:/Tindakan|Action/}).click();
 await page.getByRole("option",{name:/Selesai secara operasional|Resolved operationally/}).click();
 await region.getByRole("textbox",{name:/Tanggapan dan langkah penyelesaian|Response and resolution steps/}).fill("Synthetic replacement was received");
 await region.getByRole("button",{name:/Simpan tanggapan|Save response/}).click();
 await expect(region).toContainText("Synthetic replacement was received");
 await expect(region.getByRole("button",{name:/Simpan tanggapan|Save response/})).toHaveCount(0);
 expect((await new AxeBuilder({page}).include('main').analyze()).violations.filter(v=>["serious","critical"].includes(v.impact||""))).toEqual([]);
 await page.goto("/seller");
 await expect(page.locator(`a[href="/seller/support?issue=${issue.id}"]`)).toHaveCount(0);
 await page.request.post("/api/v1/auth/demo",{data:{role:"customer"}});
 await page.goto("/support?issue="+issue.id);
 await expect(region).toContainText("Synthetic replacement was received");
 await region.getByText(/Minta Catera meninjau|Ask Catera to review/,{exact:true}).click();
 await region.getByRole("textbox",{name:/Alasan eskalasi|Escalation reason/}).fill("Synthetic unresolved monetary question");
 await region.getByRole("button",{name:/Eskalasi ke Catera|Escalate to Catera/}).click();
 await expect(region).toContainText(/Diteruskan ke Catera|Sent to Catera/);
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await page.screenshot({path:`output/beta-improvement/issues-${locale}.png`,fullPage:true});
});
