import {test,expect} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import fs from 'node:fs';

test('marketplace section links preserve state and dropdowns work by keyboard and touch',async({page})=>{
  const errors:string[]=[];
  page.on('pageerror',error=>errors.push(error.message));
  await page.goto('/');
  await page.getByRole('combobox',{name:'Area pengantaran'}).click();
  await expect(page.getByRole('listbox')).toBeVisible();
  await page.getByRole('option',{name:'Jakarta Selatan',exact:true}).click();
  await expect(page.getByRole('combobox',{name:'Area pengantaran'})).toContainText('Jakarta Selatan');
  await page.locator('.desktop-nav').getByRole('link',{name:'Cara berlangganan'}).click();
  await expect(page).toHaveURL(/\/#how-it-works$/);
  await expect(page.locator('#how-it-works')).toBeInViewport();
  expect(await page.evaluate(()=>scrollY)).toBeGreaterThan(0);
  await page.locator('.desktop-nav').getByRole('link',{name:'Jelajah katering'}).click();
  await expect(page).toHaveURL(/\/#packages$/);
  await expect(page.getByRole('combobox',{name:'Area pengantaran'})).toContainText('Jakarta Selatan');
  await page.evaluate(()=>{(window as typeof window & {navigationSentinel?:boolean}).navigationSentinel=true;});
  await page.locator('.desktop-nav').getByRole('link',{name:'Cara berlangganan'}).click();
  expect(await page.evaluate(()=>(window as typeof window & {navigationSentinel?:boolean}).navigationSentinel)).toBe(true);
  const language=page.getByRole('combobox',{name:'Bahasa',exact:true});
  await language.focus(); await language.press('ArrowDown');
  await page.getByRole('option',{name:'English',exact:true}).click();
  await expect(page.locator('html')).toHaveAttribute('lang','en');
  await expect(page.getByRole('combobox',{name:'Language',exact:true})).toContainText('EN');
  await page.reload();
  await expect(page.locator('html')).toHaveAttribute('lang','en');
  await page.setViewportSize({width:390,height:844});
  await page.goto('/');
  await page.getByRole('combobox',{name:'Area pengantaran'}).click();
  const list=page.getByRole('listbox');
  const bounds=await list.boundingBox();
  expect(bounds!.x).toBeGreaterThanOrEqual(0);
  expect(bounds!.x+bounds!.width).toBeLessThanOrEqual(390);
  const audit=await new AxeBuilder({page}).include('[role="listbox"]').analyze();
  expect(audit.violations.filter(v=>['serious','critical'].includes(v.impact||''))).toEqual([]);
  fs.mkdirSync('output/fixes-verification',{recursive:true});
  await page.screenshot({path:'output/fixes-verification/area-phone.png'});
  await page.keyboard.press('Escape');
  await expect(page.getByRole('combobox',{name:'Area pengantaran'})).toBeFocused();
  await page.getByRole('combobox',{name:'Language',exact:true}).click();
  await page.screenshot({path:'output/fixes-verification/language-phone.png'});
  await page.keyboard.press('Escape');
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  expect(errors).toEqual([]);
});

test('legacy discover address redirects to the English catalog anchor',async({page})=>{
  await page.goto('/discover?source=test');
  await expect(page).toHaveURL(/\/\?source=test#packages$/);
  await expect(page.locator('#packages')).toBeVisible();
});
