-- Generated by scripts/compile-slot-menu-migration.mjs. Preserve immutable historical contents.
create or replace function v1.valid_contents_legacy(o jsonb,complete boolean) returns boolean language plpgsql immutable set search_path='' as $$
declare m jsonb;i jsonb;g jsonb;n record; meals text[]; names text[];ids text[];gids text[];
begin
 if coalesce(o->>'packageType','')='' then return true;end if;
 if o->>'packageType' not in('ala_carte','nasi_box') then return false;end if;
 meals:=case when o->>'meal'='both' then array['lunch','dinner'] else array[o->>'meal'] end;
 if jsonb_typeof(o->'menus') is distinct from 'array' or jsonb_array_length(o->'menus')>2 then return false;end if;
 names:=array[]::text[];
 for m in select * from jsonb_array_elements(o->'menus') loop
  if jsonb_typeof(m->'name') is distinct from 'string' or length(m->>'name')>1500 or jsonb_typeof(m->'description') is distinct from 'string' or length(m->>'description')>1500 or jsonb_typeof(m->'image') is distinct from 'string' or length(m->>'image')>500 then return false;end if;
  if coalesce(m->>'meal','')<>all(meals) or m->>'meal'=any(names) then return false;end if; names:=array_append(names,m->>'meal');
  if jsonb_typeof(m->'items') is distinct from 'array' or jsonb_array_length(m->'items')>60 or (complete and jsonb_array_length(m->'items')=0) then return false;end if;
  if jsonb_typeof(coalesce(m->'composition','[]'))<>'array' or jsonb_array_length(coalesce(m->'composition','[]'))>20 then return false;end if;
  gids:=array[]::text[];
  for g in select * from jsonb_array_elements(coalesce(m->'composition','[]')) loop
   if jsonb_typeof(g->'id') is distinct from 'string' or length(trim(g->>'id')) not between 1 and 80 or g->>'id'=any(gids) or jsonb_typeof(g->'name') is distinct from 'string' or length(trim(g->>'name')) not between 1 and 60 or jsonb_typeof(g->'slots') is distinct from 'number' or (g->>'slots')::numeric<>trunc((g->>'slots')::numeric) or (g->>'slots')::numeric not between 1 and 30 then return false;end if;
   gids:=array_append(gids,g->>'id');
   if complete and (select count(*) from jsonb_array_elements(m->'items') x where x->>'groupId'=g->>'id')<>(g->>'slots')::int then return false;end if;
  end loop;
  if o->>'packageType'='nasi_box' and complete and cardinality(gids)=0 then return false;end if;
  if o->>'packageType'='ala_carte' and cardinality(gids)>0 then return false;end if;
  ids:=array[]::text[];
  for i in select * from jsonb_array_elements(m->'items') loop
   if jsonb_typeof(i->'id') is distinct from 'string' or length(trim(i->>'id')) not between 1 and 80 or i->>'id'=any(ids) or jsonb_typeof(i->'name') is distinct from 'string' or length(trim(i->>'name'))>120 or (complete and length(trim(i->>'name'))=0) then return false;end if;
   ids:=array_append(ids,i->>'id');
   if (i ? 'description' and (jsonb_typeof(i->'description')<>'string' or length(i->>'description')>600)) or (i ? 'image' and (jsonb_typeof(i->'image')<>'string' or length(i->>'image')>500)) or (i ? 'serving' and (jsonb_typeof(i->'serving')<>'string' or length(i->>'serving')>100)) then return false;end if;
   if o->>'packageType'='nasi_box' and not(coalesce(i->>'groupId','')=any(gids)) then return false;end if;
   if o->>'packageType'='ala_carte' and i ? 'groupId' then return false;end if;
  end loop;
  if m ? 'nutrition' and m->'nutrition'<>'null'::jsonb then
   if jsonb_typeof(m->'nutrition')<>'object' then return false;end if;
   for n in select * from jsonb_each(m->'nutrition') loop
    if n.key not in('caloriesKcal','proteinG','carbsG','fatG') or jsonb_typeof(n.value)<>'number' or n.value::text::numeric<0 then return false;end if;
   end loop;
  end if;
 end loop;
 return not complete or names @> meals;
 exception when others then return false;
end $$;
-- Slot templates keep the existing immutable revision boundary. No listing or purchase is rewritten.
create table v1.dish_categories (
 id text primary key default gen_random_uuid()::text,
 caterer_id uuid references v1.caterers,
 name text not null check(length(trim(name)) between 1 and 60), name_en text
);
create unique index dish_categories_names on v1.dish_categories(caterer_id,lower(name));
alter table v1.dish_categories enable row level security;
insert into v1.dish_categories(id,name,name_en) values
 ('rice','Nasi','Rice'),('main','Lauk','Main dish'),('vegetable','Sayur','Vegetable'),
 ('soup','Sup','Soup'),('fruit','Buah','Fruit'),('dessert','Dessert','Dessert');
create function v1.categories(cid uuid) returns jsonb language sql stable set search_path='' as $$
 select coalesce(jsonb_agg(jsonb_build_object('id',id,'name',name,'nameEn',name_en) order by caterer_id nulls first,name),'[]')
 from v1.dish_categories where caterer_id is null or caterer_id=cid
$$;
create function v1.check_category(cid uuid,category text) returns void language plpgsql set search_path='' as $$
begin
 if not exists(select 1 from v1.dish_categories where id=category and (caterer_id is null or caterer_id=cid)) then raise exception 'INVALID_CATEGORY';end if;
end $$;
create function v1.check_slot_categories(cid uuid,menus jsonb) returns void language plpgsql set search_path='' as $$
declare m jsonb;g jsonb;
begin
 for m in select * from jsonb_array_elements(menus) loop
  if m->>'contentModel'='slots' then
   for g in select * from jsonb_array_elements(m->'composition') loop
    perform v1.check_category(cid,g->>'categoryId');
    if not exists(select 1 from v1.dish_categories where id=g->>'categoryId' and name=g->>'name') then raise exception 'INVALID_CATEGORY';end if;
   end loop;
  end if;
 end loop;
end $$;
create function v1.valid_slot_menu(m jsonb,complete boolean,template boolean) returns boolean language plpgsql immutable set search_path='' as $$
declare g jsonb;i jsonb;ids text[]:=array[]::text[];cats text[]:=array[]::text[];count_slots int:=0;
begin
 if m->>'contentModel' is distinct from 'slots' or jsonb_typeof(m->'composition') is distinct from 'array' or jsonb_array_length(m->'composition')>20
  or jsonb_typeof(m->'items') is distinct from 'array' or jsonb_array_length(m->'items')>60 then return false;end if;
 if complete and jsonb_array_length(m->'composition')=0 then return false;end if;
 for g in select * from jsonb_array_elements(m->'composition') loop
  if jsonb_typeof(g->'id') is distinct from 'string' or length(trim(g->>'id')) not between 1 and 80 or g->>'id'=any(ids)
   or jsonb_typeof(g->'categoryId') is distinct from 'string' or length(trim(g->>'categoryId')) not between 1 and 80 or g->>'categoryId'=any(cats)
   or jsonb_typeof(g->'name') is distinct from 'string' or length(trim(g->>'name')) not between 1 and 60
   or jsonb_typeof(g->'slots') is distinct from 'number' or (g->>'slots')::numeric<>trunc((g->>'slots')::numeric) or (g->>'slots')::int not between 1 and 30 then return false;end if;
  ids:=array_append(ids,g->>'id');cats:=array_append(cats,g->>'categoryId');count_slots:=count_slots+(g->>'slots')::int;
  if not template and complete and (select count(*) from jsonb_array_elements(m->'items') x where x->>'groupId'=g->>'id')<>(g->>'slots')::int then return false;end if;
 end loop;
 if count_slots>60 then return false;end if;
 if template then return jsonb_array_length(m->'items')=0 and coalesce(m->'nutrition','null')='null'::jsonb;end if;
 -- Reuse the complete legacy dish/nutrition validator after category checks.
 for i in select * from jsonb_array_elements(m->'items') loop
  if not exists(select 1 from jsonb_array_elements(m->'composition') grp where grp->>'id'=i->>'groupId' and grp->>'categoryId'=i->>'categoryId') then return false;end if;
 end loop;
 return v1.valid_contents_legacy(jsonb_build_object('packageType','nasi_box','meal',m->'meal','menus',jsonb_build_array(m)),complete);
exception when others then return false;
end $$;
create or replace function v1.valid_contents(o jsonb,complete boolean) returns boolean language plpgsql immutable set search_path='' as $$
declare m jsonb;seen text[]:=array[]::text[];meals text[];
begin
 if not exists(select 1 from jsonb_array_elements(o->'menus') x where x ? 'contentModel') then return v1.valid_contents_legacy(o,complete);end if;
 if o->>'packageType' not in('nasi_box','ala_carte') or jsonb_array_length(o->'menus')>2 then return false;end if;
 meals:=case when o->>'meal'='both' then array['lunch','dinner'] else array[o->>'meal'] end;
 for m in select * from jsonb_array_elements(o->'menus') loop
  if coalesce(m->>'meal','')<>all(meals) or m->>'meal'=any(seen) or not v1.valid_slot_menu(m,complete,true) then return false;end if;
  if jsonb_typeof(m->'name') is distinct from 'string' or length(m->>'name')>1500 or jsonb_typeof(m->'description') is distinct from 'string' or length(m->>'description')>1500 or jsonb_typeof(m->'image') is distinct from 'string' or length(m->>'image')>500 then return false;end if;
  seen:=array_append(seen,m->>'meal');
 end loop;
 return not complete or seen @> meals;
exception when others then return false;
end $$;

create function v1.menu_editable(pid uuid,rev int,dt date,meal_name text) returns boolean language sql stable set search_path='' as $$
 select dt >= (current_timestamp at time zone c.timezone)::date and not exists(
  select 1 from v1.delivery_days d join v1.subscriptions s on s.id=d.subscription_id join v1.fulfillments f on f.day_id=d.id
  where s.package_id=pid and coalesce((s.snapshot->'offer'->>'contentRevision')::int,0)=rev and d.service_date=dt and f.meal=meal_name and f.status='delivered')
 from v1.packages p join v1.caterers c on c.id=p.caterer_id where p.id=pid
$$;
create function v1.save_dated_menu(cid uuid,a jsonb) returns void language plpgsql set search_path='' as $$
declare p v1.packages;rev int;template jsonb;rowdata jsonb;o jsonb;target date;qty int;item jsonb;previous jsonb;
begin
 select * into p from v1.packages where id=(a->>'packageId')::uuid and caterer_id=cid for update;if not found then raise exception 'FORBIDDEN';end if;
 rev:=coalesce((a->>'contentRevision')::int,0);target:=(a->>'date')::date;
 select contents into o from v1.content_revisions where package_id=p.id and revision=rev;if not found then raise exception 'INVALID_INPUT';end if;
 if coalesce(a->>'meal','') not in('lunch','dinner') or (o->>'meal'<>'both' and a->>'meal'<>o->>'meal') then raise exception 'INVALID_INPUT';end if;
 select x into template from jsonb_array_elements(o->'menus') x where x->>'meal'=a->>'meal';
 if not coalesce(v1.menu_editable(p.id,rev,target,a->>'meal'),false) then raise exception 'CUTOFF';end if;
 select details,version into previous,qty from v1.menus where package_id=p.id and content_revision=rev and service_date=target and meal=a->>'meal';
 if jsonb_typeof(a->'version') is distinct from 'number' or (a->>'version')::numeric<>coalesce(qty,0) then raise exception 'CONFLICT';end if;
 rowdata:=((a->'details')-'source')||jsonb_build_object('meal',a->>'meal');
 if template->>'contentModel'='slots' then
  if not v1.valid_slot_menu(rowdata,true,false) then raise exception 'INVALID_INPUT';end if;
  if template->'composition' is distinct from rowdata->'composition' then raise exception 'COMPOSITION_CHANGED';end if;
  perform v1.check_slot_categories(cid,jsonb_build_array(rowdata));
  for item in select * from jsonb_array_elements(rowdata->'items') loop
   if item ? 'sourceDishId' and not exists(select 1 from v1.dishes d where d.id=(item->>'sourceDishId')::uuid and d.caterer_id=cid and
    (d.details->>'categoryId'=item->>'categoryId' or exists(select 1 from jsonb_array_elements(coalesce(previous->'items','[]')) old where old=item))) then raise exception 'INVALID_CATEGORY';end if;
  end loop;
 elsif coalesce(o->>'packageType','')<>'' then
  if rowdata ? 'contentModel' or not v1.valid_contents_legacy(jsonb_build_object('packageType',o->'packageType','meal',a->>'meal','menus',jsonb_build_array(rowdata)),true) then raise exception 'INVALID_INPUT';end if;
  if template->'composition' is distinct from rowdata->'composition' or (o->>'packageType'='ala_carte' and jsonb_array_length(template->'items')<>jsonb_array_length(rowdata->'items')) then raise exception 'COMPOSITION_CHANGED';end if;
 else
  if jsonb_typeof(rowdata->'name') is distinct from 'string' or length(trim(rowdata->>'name')) not between 1 and 1500 or rowdata ?| array['items','nutrition','composition','contentModel'] then raise exception 'INVALID_INPUT';end if;
 end if;
 perform v1.check_dish_sources(cid,jsonb_build_array(rowdata),case when previous is null then o->'menus' else jsonb_build_array(previous) end);
 if coalesce(o->>'packageType','')<>'' then rowdata:=rowdata||jsonb_build_object('name',v1.contents_summary(rowdata));end if;
 insert into v1.menus(package_id,content_revision,service_date,meal,details,version) values(p.id,rev,target,a->>'meal',rowdata,1)
 on conflict(package_id,content_revision,service_date,meal) do update set details=excluded.details,version=v1.menus.version+1;
 perform v1.notify(s.user_id,'menu','Menu pengantaran Anda diperbarui.','/calendar') from v1.subscriptions s join v1.delivery_days d on d.subscription_id=s.id where s.package_id=p.id and coalesce((s.snapshot->'offer'->>'contentRevision')::int,0)=rev and d.service_date=target and d.status not in('delivered','cancelled');
end $$;
create function v1.save_menu_batch(cid uuid,a jsonb) returns jsonb language plpgsql set search_path='' as $$
declare d jsonb;dates jsonb:=a->'dates';
begin
 if jsonb_typeof(dates) is distinct from 'array' or jsonb_array_length(dates) not between 1 and 31
  or (select count(distinct x->>'date') from jsonb_array_elements(dates)x)<>jsonb_array_length(dates)
  or (select count(distinct date_trunc('month',(x->>'date')::date)) from jsonb_array_elements(dates)x)<>1 then raise exception 'INVALID_INPUT';end if;
 for d in select * from jsonb_array_elements(dates) order by value->>'date' loop
  perform v1.save_dated_menu(cid,(a-'dates')||d);
 end loop;
 return jsonb_build_object('saved',jsonb_array_length(dates));
end $$;
create function v1.menu_month(u uuid,a jsonb) returns jsonb language plpgsql stable set search_path='' as $$
declare p v1.packages;rev int:=(a->>'revision')::int;dt date:=(a->>'month')::date;meal_name text:=a->>'meal';o jsonb;
begin
 select * into p from v1.packages where id=(a->>'packageId')::uuid;
 if not found or not v1.is_staff(u,p.caterer_id) then raise exception 'FORBIDDEN';end if;
 select contents into o from v1.content_revisions where package_id=p.id and revision=rev;
 if not found or meal_name not in('lunch','dinner') or (o->>'meal'<>'both' and o->>'meal'<>meal_name) or dt<>date_trunc('month',dt)::date then raise exception 'INVALID_INPUT';end if;
 return jsonb_build_object('categories',v1.categories(p.caterer_id),'dates',(
  select jsonb_agg(jsonb_build_object('date',day::date,'version',coalesce(m.version,0),'details',m.details,'editable',v1.menu_editable(p.id,rev,day::date,meal_name)) order by day)
  from generate_series(dt::timestamp,(dt+interval '1 month - 1 day')::timestamp,interval '1 day') day left join v1.menus m on m.package_id=p.id and m.content_revision=rev and m.service_date=day::date and m.meal=meal_name));
end $$;

do $install$ begin
 if to_regprocedure('public.catera_v1_command_legacy(text,jsonb,uuid)') is not null then
  execute $command$create or replace function public.catera_v1_command_legacy(action text,payload jsonb,request_id uuid) returns jsonb language plpgsql security definer set search_path='' as $$
declare u uuid:=auth.uid();a jsonb:=payload;r jsonb:='{}';old v1.receipts;hash text:=md5(action||payload::text);p v1.packages;o jsonb;c v1.checkouts;s v1.subscriptions;d v1.delivery_days;ad v1.addresses;cs v1.support_cases;ident uuid;cid uuid;target date;qty int;amt int;nextstatus text;mealstatus text;mealkey text;dt text;rowdata jsonb;rev int;dish v1.dishes;
begin
 if u is null then raise exception 'UNAUTHORIZED';end if;
 perform pg_advisory_xact_lock(hashtext(u::text));
 select * into old from v1.receipts where actor_id=u and receipts.request_id=catera_v1_command_legacy.request_id;
 if found then if old.hash<>hash then raise exception 'CONFLICT';end if;return old.result;end if;
 if action='profile.ensure' then insert into v1.profiles(id,name) values(u,coalesce(nullif(a->>'name',''),'Pelanggan')) on conflict do nothing;r:=jsonb_build_object('id',u);
 elsif action='address.save' then
  if length(a->>'line')<5 or coalesce(a->>'area','')='' then raise exception 'INVALID_INPUT';end if;
  ident:=(a->>'id')::uuid;
  if ident is null then insert into v1.addresses(user_id,label,line,area,city,instructions) values(u,a->>'label',a->>'line',a->>'area',a->>'city',coalesce(a->>'instructions','')) returning id into ident;
  else update v1.addresses set label=a->>'label',line=a->>'line',area=a->>'area',city=a->>'city',instructions=coalesce(a->>'instructions',''),version=version+1 where id=ident and user_id=u and version=(a->>'version')::int;if not found then raise exception 'CONFLICT';end if;end if;r:=jsonb_build_object('id',ident);
 elsif action='checkout.create' then
  select * into p from v1.packages where id=(a->>'packageId')::uuid for update;o:=v1.quote(u,a);if a ? 'expectedQuote' and a->'expectedQuote'<>o then raise exception 'PRICE_CHANGED';end if;
  insert into v1.checkouts(user_id,package_id,address_id,quote,expires_at) values(u,p.id,(a->>'addressId')::uuid,o,least(clock_timestamp()+interval '15 minutes',v1.cutoff(o->'offer',(o->'dates'->>0)::date))) returning * into c;
  for dt in select jsonb_array_elements_text(o->'dates') loop insert into v1.reservations values(c.id,p.id,dt::date,(a->>'portions')::int,'held');end loop;
  insert into v1.relationships values(u,p.caterer_id,o->>'source') on conflict do nothing;
  update v1.invites set used_by=u where code=a->>'invite' and caterer_id=p.caterer_id and role='customer' and used_by is null;
  insert into v1.outbox(kind,payload,dedupe) values('payment.create',jsonb_build_object('checkoutId',c.id),c.id::text);
  r:=to_jsonb(c);
 elsif action='checkout.demo_pay' then
  if coalesce(current_setting('catera.demo',true),'false')<>'true' then raise exception 'FORBIDDEN';end if;
  select * into c from v1.checkouts where id=(a->>'id')::uuid and user_id=u for update;if not found then raise exception 'FORBIDDEN';end if;
  insert into v1.payments(checkout_id,provider_id,amount,state) values(c.id,'demo-'||c.id,(c.quote->>'total')::int,'paid') on conflict(checkout_id) do nothing;
  ident:=v1.activate(c.id);r:=jsonb_build_object('id',c.id,'subscriptionId',ident);
 elsif action in('delivery.reschedule','delivery.address','delivery.status') then
  select * into d from v1.delivery_days where id=(a->>'id')::uuid;if not found then raise exception 'NOT_FOUND';end if;select * into s from v1.subscriptions where id=d.subscription_id;select * into p from v1.packages where id=s.package_id for update;
  select * into d from v1.delivery_days where id=d.id for update;
  if s.user_id<>u and not v1.is_staff(u,p.caterer_id) then raise exception 'FORBIDDEN';end if;
  if d.version is distinct from (a->>'version')::int then raise exception 'CONFLICT';end if;
  if action='delivery.status' then
   if not v1.is_staff(u,p.caterer_id) then raise exception 'FORBIDDEN';end if;if d.service_date>(clock_timestamp() at time zone (s.snapshot->'offer'->>'timezone'))::date then raise exception 'INVALID_DATE';end if;nextstatus:=a->>'status';
   mealkey:=a->>'meal';if mealkey is null then if (select count(*) from v1.fulfillments where day_id=d.id)>1 then raise exception 'INVALID_INPUT';end if;select meal into mealkey from v1.fulfillments where day_id=d.id;end if;
   select status into mealstatus from v1.fulfillments where day_id=d.id and meal=mealkey;if not found then raise exception 'INVALID_INPUT';end if;
   if not ((mealstatus='scheduled' and nextstatus='preparing') or (mealstatus='preparing' and nextstatus='out_for_delivery') or (mealstatus='out_for_delivery' and nextstatus in('delivered','issue')) or (mealstatus='issue' and nextstatus='out_for_delivery')) then raise exception 'INVALID_STATE';end if;
   update v1.fulfillments set status=nextstatus where day_id=d.id and meal=mealkey;
   if not exists(select 1 from v1.fulfillments where day_id=d.id and status<>'delivered') then nextstatus:='delivered';elsif exists(select 1 from v1.fulfillments where day_id=d.id and status='issue') then nextstatus:='issue';elsif exists(select 1 from v1.fulfillments where day_id=d.id and status='out_for_delivery') then nextstatus:='out_for_delivery';else nextstatus:='preparing';end if;
   update v1.delivery_days set status=nextstatus,version=version+1 where id=d.id;
   if not exists(select 1 from v1.delivery_days where subscription_id=s.id and status not in('delivered','cancelled')) then update v1.subscriptions set status='completed' where id=s.id;end if;
   perform v1.notify(s.user_id,'delivery',case when nextstatus='delivered' then 'Makanan sudah terkirim. Selamat menikmati!' else 'Status pengantaran Anda diperbarui.' end,'/deliveries/'||d.id);
  else
   if d.status<>'scheduled' or v1.cutoff(s.snapshot->'offer',d.service_date)<=clock_timestamp() then raise exception 'CUTOFF';end if;
   if action='delivery.address' then
    select * into ad from v1.addresses where id=(a->>'addressId')::uuid and user_id=s.user_id;if not found then raise exception 'FORBIDDEN';end if;
    if not (v1.offer(p)->'areas' ? ad.area) then raise exception 'COVERAGE';end if;
    update v1.delivery_days set address=to_jsonb(ad)-'user_id',version=version+1 where id=d.id;
   else
    if not (s.snapshot->'offer'->>'flexible')::boolean then raise exception 'FIXED_PACKAGE';end if;target:=(a->>'date')::date;
    if v1.cutoff(s.snapshot->'offer',target)<=clock_timestamp() then raise exception 'CUTOFF';end if;
    if not(s.snapshot->'offer'->'weekdays' @> to_jsonb(extract(dow from target)::int)) then raise exception 'INVALID_DATE';end if;
    if exists(select 1 from v1.delivery_days where subscription_id=s.id and service_date=target) then raise exception 'DUPLICATE_DATE';end if;
    if v1.slots(p.id,target)-v1.demand(p.id,target)<s.portions then raise exception 'CAPACITY';end if;
    if exists(select 1 from v1.subscriptions x where x.user_id=s.user_id and x.package_id=p.id and x.id<>s.id and x.status='active' and x.starts_on<=greatest(s.ends_on,target) and x.ends_on>=least(s.starts_on,target)) then raise exception 'OVERLAP';end if;
    if exists(select 1 from v1.checkouts pending where pending.user_id=s.user_id and pending.package_id=p.id and pending.id<>s.checkout_id and pending.state='pending' and pending.expires_at>clock_timestamp() and (pending.quote->'dates'->>0)::date<=greatest(s.ends_on,target) and (pending.quote->'dates'->>-1)::date>=least(s.starts_on,target)) then raise exception 'OVERLAP';end if;
    insert into v1.reservations(checkout_id,package_id,service_date,portions,state) values(s.checkout_id,p.id,target,s.portions,'confirmed') on conflict(checkout_id,service_date) do update set portions=excluded.portions,state='confirmed';
    update v1.reservations set state='released' where checkout_id=s.checkout_id and service_date=d.service_date;
    update v1.delivery_days set service_date=target,version=version+1 where id=d.id;
    update v1.subscriptions set starts_on=(select min(service_date) from v1.delivery_days where subscription_id=s.id),ends_on=(select max(service_date) from v1.delivery_days where subscription_id=s.id) where id=s.id;
   end if;perform v1.notify(s.user_id,'change','Perubahan pengantaran sudah tersimpan.','/deliveries/'||d.id);
  end if;r:=jsonb_build_object('id',d.id);
 elsif action='support.create' then
  if a->>'deliveryId' is not null then select * into d from v1.delivery_days where id=(a->>'deliveryId')::uuid;select * into s from v1.subscriptions where id=d.subscription_id;else select * into s from v1.subscriptions where id=(a->>'subscriptionId')::uuid;end if;
  if s.user_id is distinct from u then raise exception 'FORBIDDEN';end if;select * into p from v1.packages where id=s.package_id;
  insert into v1.support_cases(user_id,caterer_id,delivery_id,subscription_id,checkout_id,subject,description) values(u,p.caterer_id,d.id,s.id,s.checkout_id,a->>'subject',a->>'description') returning id into ident;
  update v1.allocations set held=greatest(held,amount-paid_out) where checkout_id=s.checkout_id;
  perform v1.notify(st.user_id,'support','Ada permintaan bantuan baru.','/seller/support') from v1.staff st where st.caterer_id=p.caterer_id;r:=jsonb_build_object('id',ident);
 elsif action in('support.respond','support.escalate','support.resolve') then
  select * into cs from v1.support_cases where id=(a->>'id')::uuid for update;if not found then raise exception 'NOT_FOUND';end if;
  if cs.status='resolved' then raise exception 'CONFLICT';end if;
  if action='support.respond' then if not v1.is_staff(u,cs.caterer_id) then raise exception 'FORBIDDEN';end if;update v1.support_cases set status='responded',resolution=a->>'response' where id=cs.id;
  elsif action='support.escalate' then if cs.user_id<>u and not v1.is_staff(u,cs.caterer_id) then raise exception 'FORBIDDEN';end if;update v1.support_cases set status='escalated' where id=cs.id;
  else
   if not v1.is_admin(u) then raise exception 'FORBIDDEN';end if;if cs.status='resolved' then raise exception 'CONFLICT';end if;if coalesce(length(a->>'reason'),0)<5 then raise exception 'INVALID_INPUT';end if;
   select * into c from v1.checkouts where id=cs.checkout_id for update;amt:=coalesce((a->>'amount')::int,0);
   if amt<0 or amt>(c.quote->>'total')::int-coalesce((select sum(amount) from v1.refunds where checkout_id=c.id and state<>'failed'),0) then raise exception 'AMOUNT_INVALID';end if;
   if amt>0 then insert into v1.refunds(case_id,checkout_id,amount) values(cs.id,c.id,amt) returning id into ident;insert into v1.outbox(kind,payload,dedupe) values('refund.create',jsonb_build_object('refundId',ident),ident::text);end if;
   if coalesce((a->>'cancelRemaining')::boolean,false) then
    select * into p from v1.packages where id=c.package_id for update;
    update v1.reservations set state='released' where checkout_id=c.id and service_date in(select service_date from v1.delivery_days where subscription_id=c.subscription_id and status in('scheduled','preparing','issue'));
    update v1.fulfillments set status='cancelled' where day_id in(select id from v1.delivery_days where subscription_id=c.subscription_id and status in('scheduled','preparing','issue'));
    update v1.delivery_days set status='cancelled',version=version+1 where subscription_id=c.subscription_id and status in('scheduled','preparing','issue');update v1.subscriptions set status='cancelled' where id=c.subscription_id;
   end if;
   update v1.support_cases set status='resolved',resolution=a->>'reason',amount=amt where id=cs.id;
   if amt=0 and not exists(select 1 from v1.support_cases where checkout_id=c.id and status<>'resolved') then update v1.allocations set held=0 where checkout_id=c.id;end if;
  end if;perform v1.notify(cs.user_id,'support','Permintaan bantuan Anda diperbarui.','/support');r:=jsonb_build_object('id',cs.id);
 elsif action='message.send' then
  cid:=(a->>'catererId')::uuid;ident:=(a->>'conversationId')::uuid;
  if ident is null then if not exists(select 1 from v1.caterers where id=cid and status='approved') then raise exception 'NOT_FOUND';end if;insert into v1.conversations(customer_id,caterer_id) values(u,cid) on conflict(customer_id,caterer_id) do update set customer_id=excluded.customer_id returning id into ident;
  else if not exists(select 1 from v1.conversations where id=ident and (customer_id=u or v1.is_staff(u,caterer_id))) then raise exception 'FORBIDDEN';end if;end if;
  insert into v1.messages(conversation_id,sender_id,body) values(ident,u,trim(a->>'body'));
  perform v1.notify(v.customer_id,'message','Pesan baru dari katerer.','/messages') from v1.conversations v where v.id=ident and v.customer_id<>u;
  perform v1.notify(st.user_id,'message','Pesan baru dari pelanggan.','/seller/support') from v1.staff st join v1.conversations v on v.caterer_id=st.caterer_id where v.id=ident and v.customer_id=u;
  r:=jsonb_build_object('id',ident);
 elsif action='review.save' then
  select * into s from v1.subscriptions where id=(a->>'subscriptionId')::uuid and user_id=u;if not found or not exists(select 1 from v1.delivery_days where subscription_id=s.id and status='delivered') then raise exception 'FORBIDDEN';end if;
  insert into v1.reviews(subscription_id,user_id,package_id,rating,food,delivery,value,body) values(s.id,u,s.package_id,(a->>'rating')::int,(a->>'food')::int,(a->>'delivery')::int,(a->>'value')::int,a->>'body') on conflict(subscription_id) do update set rating=excluded.rating,food=excluded.food,delivery=excluded.delivery,value=excluded.value,body=excluded.body returning id into ident;r:=jsonb_build_object('id',ident);
 elsif action='review.reply' then
  if not exists(select 1 from v1.reviews review join v1.packages pack on pack.id=review.package_id where review.id=(a->>'id')::uuid and v1.is_staff(u,pack.caterer_id)) then raise exception 'FORBIDDEN';end if;update v1.reviews set reply=a->>'reply' where id=(a->>'id')::uuid;
 elsif action='seller.create' then
  insert into v1.caterers(slug,name,description,areas) values(a->>'slug',a->>'name',a->>'description',array(select jsonb_array_elements_text(a->'areas'))) returning id into ident;insert into v1.staff values(ident,u,'owner');update v1.profiles set role='owner' where id=u;r:=jsonb_build_object('id',ident);
 elsif action in('category.save','menu.saveBatch','dish.save','dish.archive','seller.save','seller.submit','staff.invite','package.save','capacity.save','menu.save','production.freeze','import.preview','import.commit') then
  cid:=(a->>'catererId')::uuid;if not v1.is_staff(u,cid,action<>'production.freeze') then raise exception 'FORBIDDEN';end if;
  if action='seller.save' then update v1.caterers set name=a->>'name',description=a->>'description',areas=array(select jsonb_array_elements_text(a->'areas')),cutoff=(a->>'cutoff')::time,version=version+1 where id=cid and version=(a->>'version')::int;if not found then raise exception 'CONFLICT';end if;
  elsif action='seller.submit' then if not exists(select 1 from v1.packages where caterer_id=cid) then raise exception 'INVALID_INPUT';end if;update v1.caterers set status='submitted',version=version+1 where id=cid and status in('draft','corrections');if not found then raise exception 'CONFLICT';end if;
  elsif action='staff.invite' then insert into v1.invites(caterer_id,role) values(cid,'staff') returning id into ident;r:=(select to_jsonb(i) from v1.invites i where id=ident);
  elsif action='category.save' then
   if jsonb_typeof(a->'name') is distinct from 'string' or length(trim(a->>'name')) not between 1 and 60 then raise exception 'INVALID_INPUT';end if;
   perform 1 from v1.caterers where id=cid for update;
   if exists(select 1 from v1.dish_categories where (caterer_id is null or caterer_id=cid) and lower(name)=lower(trim(a->>'name'))) then raise exception 'CONFLICT';end if;
   insert into v1.dish_categories(caterer_id,name) values(cid,trim(a->>'name')) returning jsonb_build_object('id',id,'name',name) into r;
  elsif action in('dish.save','dish.archive') then
   ident:=(a->>'id')::uuid;
   if ident is not null then
    select * into dish from v1.dishes where id=ident and caterer_id=cid for update;
    if not found then raise exception 'FORBIDDEN';end if;
    if jsonb_typeof(a->'version') is distinct from 'number' or (a->>'version')::numeric<>dish.version then raise exception 'CONFLICT';end if;
   end if;
   if action='dish.save' then
    if a->'details' ? 'categoryId' then perform v1.check_category(cid,a->'details'->>'categoryId');end if;
    if not v1.valid_dish(a->'details') then raise exception 'INVALID_INPUT';end if;
    if ident is null then insert into v1.dishes(caterer_id,details) values(cid,a->'details') returning * into dish;
    else update v1.dishes set details=a->'details',version=version+1,updated_at=now() where id=ident returning * into dish;end if;
   else
    if ident is null or jsonb_typeof(a->'archived') is distinct from 'boolean' then raise exception 'INVALID_INPUT';end if;
    update v1.dishes set archived=(a->>'archived')::boolean,version=version+1,updated_at=now() where id=ident returning * into dish;
   end if;
   ident:=dish.id;r:=v1.library_dish(dish);
  elsif action='package.save' then
   if not v1.valid_offer(a->'offer') then raise exception 'INVALID_INPUT';end if;
   ident:=(a->>'id')::uuid;
   if ident is not null then select * into p from v1.packages where id=ident and caterer_id=cid for update;if not found then raise exception 'FORBIDDEN';end if;end if;
   if coalesce(a->'offer'->>'packageType','')='' and a->'offer'->>'status'<>'draft' and (ident is null or coalesce((p.offer->>'contentRevision')::int,0)>0 or v1.contents_template(a->'offer') is distinct from v1.contents_template(p.offer)) then raise exception 'CLASSIFY_PACKAGE';end if;
   perform v1.check_slot_categories(cid,a->'offer'->'menus');
   perform v1.check_dish_sources(cid,a->'offer'->'menus',p.offer->'menus');
   o:=(a->'offer')-'contentRevision';
   if coalesce(o->>'packageType','')<>'' then
    o:=jsonb_set(o,'{menus}',(select coalesce(jsonb_agg((m-'source')||jsonb_build_object('name',v1.contents_summary(m))),'[]') from jsonb_array_elements(o->'menus') m));
   end if;
   rev:=case when ident is null then 1 when v1.contents_template(o)=v1.contents_template(p.offer) then coalesce((p.offer->>'contentRevision')::int,0) else coalesce((select max(revision) from v1.content_revisions where package_id=ident),0)+1 end;
   a:=jsonb_set(a,'{offer}',o||jsonb_build_object('contentRevision',rev));
   if ident is null then insert into v1.packages(caterer_id,slug,offer,status) values(cid,a->>'slug',a->'offer',a->'offer'->>'status') returning id into ident;
   else select * into p from v1.packages where id=ident and caterer_id=cid for update;if not found then raise exception 'FORBIDDEN';end if;
    for target in select distinct service_date from v1.reservations where package_id=ident and state<>'released' and service_date>=current_date loop
     if not exists(select 1 from v1.capacity where package_id=ident and service_date=target) and coalesce((a->'offer'->'capacity'->>extract(dow from target)::int::text)::int,0)<v1.demand(ident,target) then raise exception 'CAPACITY';end if;
    end loop;
    update v1.packages set offer=a->'offer',status=a->'offer'->>'status',version=version+1 where id=ident and caterer_id=cid and version=(a->>'version')::int;if not found then raise exception 'CONFLICT';end if;
   end if;
   insert into v1.content_revisions(package_id,revision,contents) values(ident,rev,v1.contents_template(a->'offer')) on conflict do nothing;
   r:=jsonb_build_object('id',ident,'contentRevision',rev);
  elsif action='capacity.save' then
   select * into p from v1.packages where id=(a->>'packageId')::uuid and caterer_id=cid for update;if not found then raise exception 'FORBIDDEN';end if;target:=(a->>'date')::date;qty:=(a->>'slots')::int;
   if qty<v1.demand(p.id,target) or (coalesce((a->>'closed')::boolean,false) and v1.demand(p.id,target)>0) then raise exception 'CAPACITY';end if;
   insert into v1.capacity values(p.id,target,qty,coalesce((a->>'closed')::boolean,false)) on conflict(package_id,service_date) do update set slots=excluded.slots,closed=excluded.closed;
  elsif action='menu.save' then
   perform v1.save_dated_menu(cid,a);
  elsif action='menu.saveBatch' then
   r:=v1.save_menu_batch(cid,a);
  elsif action='production.freeze' then
   perform 1 from v1.caterers where id=cid for update;target:=(a->>'date')::date;select coalesce(max(revision),0)+1 into rev from v1.production where caterer_id=cid and service_date=target;
   insert into v1.production(caterer_id,service_date,revision,entries) values(cid,target,rev,coalesce((select jsonb_agg(v1.delivery(day)) from v1.delivery_days day join v1.subscriptions sub on sub.id=day.subscription_id join v1.packages pack on pack.id=sub.package_id where pack.caterer_id=cid and day.service_date=target and day.status<>'cancelled'),'[]')) returning id into ident;r:=jsonb_build_object('id',ident,'revision',rev);
  elsif action='import.preview' then
   if jsonb_array_length(a->'rows')>100 then raise exception 'INVALID_INPUT';end if;
   o:='[]';for rowdata in select * from jsonb_array_elements(a->'rows') loop
    if not exists(select 1 from v1.packages where id=(rowdata->>'packageId')::uuid and caterer_id=cid) or not exists(select 1 from v1.profiles where id=(rowdata->>'customerId')::uuid) then raise exception 'INVALID_INPUT';end if;
    r:=v1.import_quote((rowdata->>'customerId')::uuid,rowdata);o:=o||jsonb_build_object('customerId',rowdata->>'customerId','addressId',rowdata->>'addressId','packageId',rowdata->>'packageId','portions',rowdata->'portions','startDate',rowdata->>'startDate','remainingDays',rowdata->'remainingDays','externalReference',rowdata->>'externalReference','preview',r);
   end loop;insert into v1.imports(caterer_id,created_by,rows) values(cid,u,o) returning id into ident;r:=jsonb_build_object('id',ident,'rows',o);
  else
   select rows into o from v1.imports where id=(a->>'id')::uuid and caterer_id=cid and state='preview' for update;if not found then raise exception 'CONFLICT';end if;
   perform 1 from v1.packages where id in(select (j->>'packageId')::uuid from jsonb_array_elements(o) j) order by id for update;
   for rowdata in select * from jsonb_array_elements(o) loop
    select * into p from v1.packages where id=(rowdata->>'packageId')::uuid for update;
    insert into v1.relationships values((rowdata->>'customerId')::uuid,cid,'legacy') on conflict do nothing;
    rowdata:=rowdata||jsonb_build_object('trial',false,'promo','','invite','');
    r:=v1.import_quote((rowdata->>'customerId')::uuid,rowdata);
    insert into v1.checkouts(user_id,package_id,address_id,quote,expires_at) values((rowdata->>'customerId')::uuid,p.id,(rowdata->>'addressId')::uuid,r,now()+interval '15 minutes') returning id into ident;
    for dt in select jsonb_array_elements_text(r->'dates') loop insert into v1.reservations values(ident,p.id,dt::date,(r->>'portions')::int,'held');end loop;
    ident:=v1.activate(ident);update v1.subscriptions set legacy=true where id=ident;delete from v1.allocations where checkout_id=(select checkout_id from v1.subscriptions where id=ident);
   end loop;update v1.imports set state='committed' where id=(a->>'id')::uuid;r:=jsonb_build_object('id',a->>'id');
  end if;
 elsif action in('admin.verify','promotion.save','review.moderate','payout.approve') then
  if not v1.is_admin(u) then raise exception 'FORBIDDEN';end if;
  if action in('admin.verify','review.moderate','payout.approve') and coalesce(length(a->>'reason'),0)<5 then raise exception 'INVALID_INPUT';end if;
  if action='admin.verify' then update v1.caterers set status=a->>'status',review_note=a->>'reason',version=version+1 where id=(a->>'id')::uuid and version=(a->>'version')::int;if not found then raise exception 'CONFLICT';end if;
  elsif action='promotion.save' then insert into v1.promotions(code,percent,active) values(upper(a->>'code'),(a->>'percent')::int,(a->>'active')::boolean) on conflict(code) do update set percent=excluded.percent,active=excluded.active;
  elsif action='review.moderate' then update v1.reviews set hidden=(a->>'hidden')::boolean where id=(a->>'id')::uuid;
  else
   cid:=(a->>'catererId')::uuid;perform 1 from v1.caterers where id=cid for update;select coalesce(sum(amount-held-paid_out),0) into amt from v1.allocations where caterer_id=cid;
   if amt<=0 then raise exception 'AMOUNT_INVALID';end if;insert into v1.payouts(caterer_id,amount) values(cid,amt) returning id into ident;
   insert into v1.payout_items select ident,id,amount-held-paid_out from v1.allocations where caterer_id=cid and amount-held-paid_out>0;
   update v1.allocations set paid_out=amount-held where caterer_id=cid;insert into v1.outbox(kind,payload,dedupe) values('payout.create',jsonb_build_object('payoutId',ident),ident::text);r:=jsonb_build_object('id',ident);
  end if;
 elsif action='notification.read' then update v1.notifications set read_at=now() where user_id=u and id=(a->>'id')::uuid;
 elsif action='device.register' then insert into v1.devices(user_id,token) values(u,a->>'token') on conflict(token) do update set user_id=u;
 elsif action='invite.accept' then
  select caterer_id into cid from v1.invites where code=a->>'code' and role='staff' and used_by is null for update;if not found then raise exception 'NOT_FOUND';end if;
  insert into v1.staff values(cid,u,'staff') on conflict do nothing;update v1.invites set used_by=u where code=a->>'code';update v1.profiles set role='staff' where id=u and role='customer';
 else raise exception 'INVALID_ACTION';end if;
 insert into v1.audit(actor_id,action,details) values(u,action,jsonb_build_object('id',coalesce(r->>'id',a->>'id'),'requestId',request_id,'reason',coalesce(a->>'reason',a->>'response'),'dateBefore',d.service_date,'dateAfter',a->>'date','versionBefore',d.version,'amount',a->>'amount','status',a->>'status','catererId',coalesce(cid,p.caterer_id),'customerId',s.user_id));
 insert into v1.receipts values(u,request_id,hash,r);return r;
end $$;$command$;
 else execute $command$create or replace function public.catera_v1_command(action text,payload jsonb,request_id uuid) returns jsonb language plpgsql security definer set search_path='' as $$
declare u uuid:=auth.uid();a jsonb:=payload;r jsonb:='{}';old v1.receipts;hash text:=md5(action||payload::text);p v1.packages;o jsonb;c v1.checkouts;s v1.subscriptions;d v1.delivery_days;ad v1.addresses;cs v1.support_cases;ident uuid;cid uuid;target date;qty int;amt int;nextstatus text;mealstatus text;mealkey text;dt text;rowdata jsonb;rev int;dish v1.dishes;
begin
 if u is null then raise exception 'UNAUTHORIZED';end if;
 perform pg_advisory_xact_lock(hashtext(u::text));
 select * into old from v1.receipts where actor_id=u and receipts.request_id=catera_v1_command.request_id;
 if found then if old.hash<>hash then raise exception 'CONFLICT';end if;return old.result;end if;
 if action='profile.ensure' then insert into v1.profiles(id,name) values(u,coalesce(nullif(a->>'name',''),'Pelanggan')) on conflict do nothing;r:=jsonb_build_object('id',u);
 elsif action='address.save' then
  if length(a->>'line')<5 or coalesce(a->>'area','')='' then raise exception 'INVALID_INPUT';end if;
  ident:=(a->>'id')::uuid;
  if ident is null then insert into v1.addresses(user_id,label,line,area,city,instructions) values(u,a->>'label',a->>'line',a->>'area',a->>'city',coalesce(a->>'instructions','')) returning id into ident;
  else update v1.addresses set label=a->>'label',line=a->>'line',area=a->>'area',city=a->>'city',instructions=coalesce(a->>'instructions',''),version=version+1 where id=ident and user_id=u and version=(a->>'version')::int;if not found then raise exception 'CONFLICT';end if;end if;r:=jsonb_build_object('id',ident);
 elsif action='checkout.create' then
  select * into p from v1.packages where id=(a->>'packageId')::uuid for update;o:=v1.quote(u,a);if a ? 'expectedQuote' and a->'expectedQuote'<>o then raise exception 'PRICE_CHANGED';end if;
  insert into v1.checkouts(user_id,package_id,address_id,quote,expires_at) values(u,p.id,(a->>'addressId')::uuid,o,least(clock_timestamp()+interval '15 minutes',v1.cutoff(o->'offer',(o->'dates'->>0)::date))) returning * into c;
  for dt in select jsonb_array_elements_text(o->'dates') loop insert into v1.reservations values(c.id,p.id,dt::date,(a->>'portions')::int,'held');end loop;
  insert into v1.relationships values(u,p.caterer_id,o->>'source') on conflict do nothing;
  update v1.invites set used_by=u where code=a->>'invite' and caterer_id=p.caterer_id and role='customer' and used_by is null;
  insert into v1.outbox(kind,payload,dedupe) values('payment.create',jsonb_build_object('checkoutId',c.id),c.id::text);
  r:=to_jsonb(c);
 elsif action='checkout.demo_pay' then
  if coalesce(current_setting('catera.demo',true),'false')<>'true' then raise exception 'FORBIDDEN';end if;
  select * into c from v1.checkouts where id=(a->>'id')::uuid and user_id=u for update;if not found then raise exception 'FORBIDDEN';end if;
  insert into v1.payments(checkout_id,provider_id,amount,state) values(c.id,'demo-'||c.id,(c.quote->>'total')::int,'paid') on conflict(checkout_id) do nothing;
  ident:=v1.activate(c.id);r:=jsonb_build_object('id',c.id,'subscriptionId',ident);
 elsif action in('delivery.reschedule','delivery.address','delivery.status') then
  select * into d from v1.delivery_days where id=(a->>'id')::uuid;if not found then raise exception 'NOT_FOUND';end if;select * into s from v1.subscriptions where id=d.subscription_id;select * into p from v1.packages where id=s.package_id for update;
  select * into d from v1.delivery_days where id=d.id for update;
  if s.user_id<>u and not v1.is_staff(u,p.caterer_id) then raise exception 'FORBIDDEN';end if;
  if d.version is distinct from (a->>'version')::int then raise exception 'CONFLICT';end if;
  if action='delivery.status' then
   if not v1.is_staff(u,p.caterer_id) then raise exception 'FORBIDDEN';end if;if d.service_date>(clock_timestamp() at time zone (s.snapshot->'offer'->>'timezone'))::date then raise exception 'INVALID_DATE';end if;nextstatus:=a->>'status';
   mealkey:=a->>'meal';if mealkey is null then if (select count(*) from v1.fulfillments where day_id=d.id)>1 then raise exception 'INVALID_INPUT';end if;select meal into mealkey from v1.fulfillments where day_id=d.id;end if;
   select status into mealstatus from v1.fulfillments where day_id=d.id and meal=mealkey;if not found then raise exception 'INVALID_INPUT';end if;
   if not ((mealstatus='scheduled' and nextstatus='preparing') or (mealstatus='preparing' and nextstatus='out_for_delivery') or (mealstatus='out_for_delivery' and nextstatus in('delivered','issue')) or (mealstatus='issue' and nextstatus='out_for_delivery')) then raise exception 'INVALID_STATE';end if;
   update v1.fulfillments set status=nextstatus where day_id=d.id and meal=mealkey;
   if not exists(select 1 from v1.fulfillments where day_id=d.id and status<>'delivered') then nextstatus:='delivered';elsif exists(select 1 from v1.fulfillments where day_id=d.id and status='issue') then nextstatus:='issue';elsif exists(select 1 from v1.fulfillments where day_id=d.id and status='out_for_delivery') then nextstatus:='out_for_delivery';else nextstatus:='preparing';end if;
   update v1.delivery_days set status=nextstatus,version=version+1 where id=d.id;
   if not exists(select 1 from v1.delivery_days where subscription_id=s.id and status not in('delivered','cancelled')) then update v1.subscriptions set status='completed' where id=s.id;end if;
   perform v1.notify(s.user_id,'delivery',case when nextstatus='delivered' then 'Makanan sudah terkirim. Selamat menikmati!' else 'Status pengantaran Anda diperbarui.' end,'/deliveries/'||d.id);
  else
   if d.status<>'scheduled' or v1.cutoff(s.snapshot->'offer',d.service_date)<=clock_timestamp() then raise exception 'CUTOFF';end if;
   if action='delivery.address' then
    select * into ad from v1.addresses where id=(a->>'addressId')::uuid and user_id=s.user_id;if not found then raise exception 'FORBIDDEN';end if;
    if not (v1.offer(p)->'areas' ? ad.area) then raise exception 'COVERAGE';end if;
    update v1.delivery_days set address=to_jsonb(ad)-'user_id',version=version+1 where id=d.id;
   else
    if not (s.snapshot->'offer'->>'flexible')::boolean then raise exception 'FIXED_PACKAGE';end if;target:=(a->>'date')::date;
    if v1.cutoff(s.snapshot->'offer',target)<=clock_timestamp() then raise exception 'CUTOFF';end if;
    if not(s.snapshot->'offer'->'weekdays' @> to_jsonb(extract(dow from target)::int)) then raise exception 'INVALID_DATE';end if;
    if exists(select 1 from v1.delivery_days where subscription_id=s.id and service_date=target) then raise exception 'DUPLICATE_DATE';end if;
    if v1.slots(p.id,target)-v1.demand(p.id,target)<s.portions then raise exception 'CAPACITY';end if;
    if exists(select 1 from v1.subscriptions x where x.user_id=s.user_id and x.package_id=p.id and x.id<>s.id and x.status='active' and x.starts_on<=greatest(s.ends_on,target) and x.ends_on>=least(s.starts_on,target)) then raise exception 'OVERLAP';end if;
    if exists(select 1 from v1.checkouts pending where pending.user_id=s.user_id and pending.package_id=p.id and pending.id<>s.checkout_id and pending.state='pending' and pending.expires_at>clock_timestamp() and (pending.quote->'dates'->>0)::date<=greatest(s.ends_on,target) and (pending.quote->'dates'->>-1)::date>=least(s.starts_on,target)) then raise exception 'OVERLAP';end if;
    insert into v1.reservations(checkout_id,package_id,service_date,portions,state) values(s.checkout_id,p.id,target,s.portions,'confirmed') on conflict(checkout_id,service_date) do update set portions=excluded.portions,state='confirmed';
    update v1.reservations set state='released' where checkout_id=s.checkout_id and service_date=d.service_date;
    update v1.delivery_days set service_date=target,version=version+1 where id=d.id;
    update v1.subscriptions set starts_on=(select min(service_date) from v1.delivery_days where subscription_id=s.id),ends_on=(select max(service_date) from v1.delivery_days where subscription_id=s.id) where id=s.id;
   end if;perform v1.notify(s.user_id,'change','Perubahan pengantaran sudah tersimpan.','/deliveries/'||d.id);
  end if;r:=jsonb_build_object('id',d.id);
 elsif action='support.create' then
  if a->>'deliveryId' is not null then select * into d from v1.delivery_days where id=(a->>'deliveryId')::uuid;select * into s from v1.subscriptions where id=d.subscription_id;else select * into s from v1.subscriptions where id=(a->>'subscriptionId')::uuid;end if;
  if s.user_id is distinct from u then raise exception 'FORBIDDEN';end if;select * into p from v1.packages where id=s.package_id;
  insert into v1.support_cases(user_id,caterer_id,delivery_id,subscription_id,checkout_id,subject,description) values(u,p.caterer_id,d.id,s.id,s.checkout_id,a->>'subject',a->>'description') returning id into ident;
  update v1.allocations set held=greatest(held,amount-paid_out) where checkout_id=s.checkout_id;
  perform v1.notify(st.user_id,'support','Ada permintaan bantuan baru.','/seller/support') from v1.staff st where st.caterer_id=p.caterer_id;r:=jsonb_build_object('id',ident);
 elsif action in('support.respond','support.escalate','support.resolve') then
  select * into cs from v1.support_cases where id=(a->>'id')::uuid for update;if not found then raise exception 'NOT_FOUND';end if;
  if cs.status='resolved' then raise exception 'CONFLICT';end if;
  if action='support.respond' then if not v1.is_staff(u,cs.caterer_id) then raise exception 'FORBIDDEN';end if;update v1.support_cases set status='responded',resolution=a->>'response' where id=cs.id;
  elsif action='support.escalate' then if cs.user_id<>u and not v1.is_staff(u,cs.caterer_id) then raise exception 'FORBIDDEN';end if;update v1.support_cases set status='escalated' where id=cs.id;
  else
   if not v1.is_admin(u) then raise exception 'FORBIDDEN';end if;if cs.status='resolved' then raise exception 'CONFLICT';end if;if coalesce(length(a->>'reason'),0)<5 then raise exception 'INVALID_INPUT';end if;
   select * into c from v1.checkouts where id=cs.checkout_id for update;amt:=coalesce((a->>'amount')::int,0);
   if amt<0 or amt>(c.quote->>'total')::int-coalesce((select sum(amount) from v1.refunds where checkout_id=c.id and state<>'failed'),0) then raise exception 'AMOUNT_INVALID';end if;
   if amt>0 then insert into v1.refunds(case_id,checkout_id,amount) values(cs.id,c.id,amt) returning id into ident;insert into v1.outbox(kind,payload,dedupe) values('refund.create',jsonb_build_object('refundId',ident),ident::text);end if;
   if coalesce((a->>'cancelRemaining')::boolean,false) then
    select * into p from v1.packages where id=c.package_id for update;
    update v1.reservations set state='released' where checkout_id=c.id and service_date in(select service_date from v1.delivery_days where subscription_id=c.subscription_id and status in('scheduled','preparing','issue'));
    update v1.fulfillments set status='cancelled' where day_id in(select id from v1.delivery_days where subscription_id=c.subscription_id and status in('scheduled','preparing','issue'));
    update v1.delivery_days set status='cancelled',version=version+1 where subscription_id=c.subscription_id and status in('scheduled','preparing','issue');update v1.subscriptions set status='cancelled' where id=c.subscription_id;
   end if;
   update v1.support_cases set status='resolved',resolution=a->>'reason',amount=amt where id=cs.id;
   if amt=0 and not exists(select 1 from v1.support_cases where checkout_id=c.id and status<>'resolved') then update v1.allocations set held=0 where checkout_id=c.id;end if;
  end if;perform v1.notify(cs.user_id,'support','Permintaan bantuan Anda diperbarui.','/support');r:=jsonb_build_object('id',cs.id);
 elsif action='message.send' then
  cid:=(a->>'catererId')::uuid;ident:=(a->>'conversationId')::uuid;
  if ident is null then if not exists(select 1 from v1.caterers where id=cid and status='approved') then raise exception 'NOT_FOUND';end if;insert into v1.conversations(customer_id,caterer_id) values(u,cid) on conflict(customer_id,caterer_id) do update set customer_id=excluded.customer_id returning id into ident;
  else if not exists(select 1 from v1.conversations where id=ident and (customer_id=u or v1.is_staff(u,caterer_id))) then raise exception 'FORBIDDEN';end if;end if;
  insert into v1.messages(conversation_id,sender_id,body) values(ident,u,trim(a->>'body'));
  perform v1.notify(v.customer_id,'message','Pesan baru dari katerer.','/messages') from v1.conversations v where v.id=ident and v.customer_id<>u;
  perform v1.notify(st.user_id,'message','Pesan baru dari pelanggan.','/seller/support') from v1.staff st join v1.conversations v on v.caterer_id=st.caterer_id where v.id=ident and v.customer_id=u;
  r:=jsonb_build_object('id',ident);
 elsif action='review.save' then
  select * into s from v1.subscriptions where id=(a->>'subscriptionId')::uuid and user_id=u;if not found or not exists(select 1 from v1.delivery_days where subscription_id=s.id and status='delivered') then raise exception 'FORBIDDEN';end if;
  insert into v1.reviews(subscription_id,user_id,package_id,rating,food,delivery,value,body) values(s.id,u,s.package_id,(a->>'rating')::int,(a->>'food')::int,(a->>'delivery')::int,(a->>'value')::int,a->>'body') on conflict(subscription_id) do update set rating=excluded.rating,food=excluded.food,delivery=excluded.delivery,value=excluded.value,body=excluded.body returning id into ident;r:=jsonb_build_object('id',ident);
 elsif action='review.reply' then
  if not exists(select 1 from v1.reviews review join v1.packages pack on pack.id=review.package_id where review.id=(a->>'id')::uuid and v1.is_staff(u,pack.caterer_id)) then raise exception 'FORBIDDEN';end if;update v1.reviews set reply=a->>'reply' where id=(a->>'id')::uuid;
 elsif action='seller.create' then
  insert into v1.caterers(slug,name,description,areas) values(a->>'slug',a->>'name',a->>'description',array(select jsonb_array_elements_text(a->'areas'))) returning id into ident;insert into v1.staff values(ident,u,'owner');update v1.profiles set role='owner' where id=u;r:=jsonb_build_object('id',ident);
 elsif action in('category.save','menu.saveBatch','dish.save','dish.archive','seller.save','seller.submit','staff.invite','package.save','capacity.save','menu.save','production.freeze','import.preview','import.commit') then
  cid:=(a->>'catererId')::uuid;if not v1.is_staff(u,cid,action<>'production.freeze') then raise exception 'FORBIDDEN';end if;
  if action='seller.save' then update v1.caterers set name=a->>'name',description=a->>'description',areas=array(select jsonb_array_elements_text(a->'areas')),cutoff=(a->>'cutoff')::time,version=version+1 where id=cid and version=(a->>'version')::int;if not found then raise exception 'CONFLICT';end if;
  elsif action='seller.submit' then if not exists(select 1 from v1.packages where caterer_id=cid) then raise exception 'INVALID_INPUT';end if;update v1.caterers set status='submitted',version=version+1 where id=cid and status in('draft','corrections');if not found then raise exception 'CONFLICT';end if;
  elsif action='staff.invite' then insert into v1.invites(caterer_id,role) values(cid,'staff') returning id into ident;r:=(select to_jsonb(i) from v1.invites i where id=ident);
  elsif action='category.save' then
   if jsonb_typeof(a->'name') is distinct from 'string' or length(trim(a->>'name')) not between 1 and 60 then raise exception 'INVALID_INPUT';end if;
   perform 1 from v1.caterers where id=cid for update;
   if exists(select 1 from v1.dish_categories where (caterer_id is null or caterer_id=cid) and lower(name)=lower(trim(a->>'name'))) then raise exception 'CONFLICT';end if;
   insert into v1.dish_categories(caterer_id,name) values(cid,trim(a->>'name')) returning jsonb_build_object('id',id,'name',name) into r;
  elsif action in('dish.save','dish.archive') then
   ident:=(a->>'id')::uuid;
   if ident is not null then
    select * into dish from v1.dishes where id=ident and caterer_id=cid for update;
    if not found then raise exception 'FORBIDDEN';end if;
    if jsonb_typeof(a->'version') is distinct from 'number' or (a->>'version')::numeric<>dish.version then raise exception 'CONFLICT';end if;
   end if;
   if action='dish.save' then
    if a->'details' ? 'categoryId' then perform v1.check_category(cid,a->'details'->>'categoryId');end if;
    if not v1.valid_dish(a->'details') then raise exception 'INVALID_INPUT';end if;
    if ident is null then insert into v1.dishes(caterer_id,details) values(cid,a->'details') returning * into dish;
    else update v1.dishes set details=a->'details',version=version+1,updated_at=now() where id=ident returning * into dish;end if;
   else
    if ident is null or jsonb_typeof(a->'archived') is distinct from 'boolean' then raise exception 'INVALID_INPUT';end if;
    update v1.dishes set archived=(a->>'archived')::boolean,version=version+1,updated_at=now() where id=ident returning * into dish;
   end if;
   ident:=dish.id;r:=v1.library_dish(dish);
  elsif action='package.save' then
   if not v1.valid_offer(a->'offer') then raise exception 'INVALID_INPUT';end if;
   ident:=(a->>'id')::uuid;
   if ident is not null then select * into p from v1.packages where id=ident and caterer_id=cid for update;if not found then raise exception 'FORBIDDEN';end if;end if;
   if coalesce(a->'offer'->>'packageType','')='' and a->'offer'->>'status'<>'draft' and (ident is null or coalesce((p.offer->>'contentRevision')::int,0)>0 or v1.contents_template(a->'offer') is distinct from v1.contents_template(p.offer)) then raise exception 'CLASSIFY_PACKAGE';end if;
   perform v1.check_slot_categories(cid,a->'offer'->'menus');
   perform v1.check_dish_sources(cid,a->'offer'->'menus',p.offer->'menus');
   o:=(a->'offer')-'contentRevision';
   if coalesce(o->>'packageType','')<>'' then
    o:=jsonb_set(o,'{menus}',(select coalesce(jsonb_agg((m-'source')||jsonb_build_object('name',v1.contents_summary(m))),'[]') from jsonb_array_elements(o->'menus') m));
   end if;
   rev:=case when ident is null then 1 when v1.contents_template(o)=v1.contents_template(p.offer) then coalesce((p.offer->>'contentRevision')::int,0) else coalesce((select max(revision) from v1.content_revisions where package_id=ident),0)+1 end;
   a:=jsonb_set(a,'{offer}',o||jsonb_build_object('contentRevision',rev));
   if ident is null then insert into v1.packages(caterer_id,slug,offer,status) values(cid,a->>'slug',a->'offer',a->'offer'->>'status') returning id into ident;
   else select * into p from v1.packages where id=ident and caterer_id=cid for update;if not found then raise exception 'FORBIDDEN';end if;
    for target in select distinct service_date from v1.reservations where package_id=ident and state<>'released' and service_date>=current_date loop
     if not exists(select 1 from v1.capacity where package_id=ident and service_date=target) and coalesce((a->'offer'->'capacity'->>extract(dow from target)::int::text)::int,0)<v1.demand(ident,target) then raise exception 'CAPACITY';end if;
    end loop;
    update v1.packages set offer=a->'offer',status=a->'offer'->>'status',version=version+1 where id=ident and caterer_id=cid and version=(a->>'version')::int;if not found then raise exception 'CONFLICT';end if;
   end if;
   insert into v1.content_revisions(package_id,revision,contents) values(ident,rev,v1.contents_template(a->'offer')) on conflict do nothing;
   r:=jsonb_build_object('id',ident,'contentRevision',rev);
  elsif action='capacity.save' then
   select * into p from v1.packages where id=(a->>'packageId')::uuid and caterer_id=cid for update;if not found then raise exception 'FORBIDDEN';end if;target:=(a->>'date')::date;qty:=(a->>'slots')::int;
   if qty<v1.demand(p.id,target) or (coalesce((a->>'closed')::boolean,false) and v1.demand(p.id,target)>0) then raise exception 'CAPACITY';end if;
   insert into v1.capacity values(p.id,target,qty,coalesce((a->>'closed')::boolean,false)) on conflict(package_id,service_date) do update set slots=excluded.slots,closed=excluded.closed;
  elsif action='menu.save' then
   perform v1.save_dated_menu(cid,a);
  elsif action='menu.saveBatch' then
   r:=v1.save_menu_batch(cid,a);
  elsif action='production.freeze' then
   perform 1 from v1.caterers where id=cid for update;target:=(a->>'date')::date;select coalesce(max(revision),0)+1 into rev from v1.production where caterer_id=cid and service_date=target;
   insert into v1.production(caterer_id,service_date,revision,entries) values(cid,target,rev,coalesce((select jsonb_agg(v1.delivery(day)) from v1.delivery_days day join v1.subscriptions sub on sub.id=day.subscription_id join v1.packages pack on pack.id=sub.package_id where pack.caterer_id=cid and day.service_date=target and day.status<>'cancelled'),'[]')) returning id into ident;r:=jsonb_build_object('id',ident,'revision',rev);
  elsif action='import.preview' then
   if jsonb_array_length(a->'rows')>100 then raise exception 'INVALID_INPUT';end if;
   o:='[]';for rowdata in select * from jsonb_array_elements(a->'rows') loop
    if not exists(select 1 from v1.packages where id=(rowdata->>'packageId')::uuid and caterer_id=cid) or not exists(select 1 from v1.profiles where id=(rowdata->>'customerId')::uuid) then raise exception 'INVALID_INPUT';end if;
    r:=v1.import_quote((rowdata->>'customerId')::uuid,rowdata);o:=o||jsonb_build_object('customerId',rowdata->>'customerId','addressId',rowdata->>'addressId','packageId',rowdata->>'packageId','portions',rowdata->'portions','startDate',rowdata->>'startDate','remainingDays',rowdata->'remainingDays','externalReference',rowdata->>'externalReference','preview',r);
   end loop;insert into v1.imports(caterer_id,created_by,rows) values(cid,u,o) returning id into ident;r:=jsonb_build_object('id',ident,'rows',o);
  else
   select rows into o from v1.imports where id=(a->>'id')::uuid and caterer_id=cid and state='preview' for update;if not found then raise exception 'CONFLICT';end if;
   perform 1 from v1.packages where id in(select (j->>'packageId')::uuid from jsonb_array_elements(o) j) order by id for update;
   for rowdata in select * from jsonb_array_elements(o) loop
    select * into p from v1.packages where id=(rowdata->>'packageId')::uuid for update;
    insert into v1.relationships values((rowdata->>'customerId')::uuid,cid,'legacy') on conflict do nothing;
    rowdata:=rowdata||jsonb_build_object('trial',false,'promo','','invite','');
    r:=v1.import_quote((rowdata->>'customerId')::uuid,rowdata);
    insert into v1.checkouts(user_id,package_id,address_id,quote,expires_at) values((rowdata->>'customerId')::uuid,p.id,(rowdata->>'addressId')::uuid,r,now()+interval '15 minutes') returning id into ident;
    for dt in select jsonb_array_elements_text(r->'dates') loop insert into v1.reservations values(ident,p.id,dt::date,(r->>'portions')::int,'held');end loop;
    ident:=v1.activate(ident);update v1.subscriptions set legacy=true where id=ident;delete from v1.allocations where checkout_id=(select checkout_id from v1.subscriptions where id=ident);
   end loop;update v1.imports set state='committed' where id=(a->>'id')::uuid;r:=jsonb_build_object('id',a->>'id');
  end if;
 elsif action in('admin.verify','promotion.save','review.moderate','payout.approve') then
  if not v1.is_admin(u) then raise exception 'FORBIDDEN';end if;
  if action in('admin.verify','review.moderate','payout.approve') and coalesce(length(a->>'reason'),0)<5 then raise exception 'INVALID_INPUT';end if;
  if action='admin.verify' then update v1.caterers set status=a->>'status',review_note=a->>'reason',version=version+1 where id=(a->>'id')::uuid and version=(a->>'version')::int;if not found then raise exception 'CONFLICT';end if;
  elsif action='promotion.save' then insert into v1.promotions(code,percent,active) values(upper(a->>'code'),(a->>'percent')::int,(a->>'active')::boolean) on conflict(code) do update set percent=excluded.percent,active=excluded.active;
  elsif action='review.moderate' then update v1.reviews set hidden=(a->>'hidden')::boolean where id=(a->>'id')::uuid;
  else
   cid:=(a->>'catererId')::uuid;perform 1 from v1.caterers where id=cid for update;select coalesce(sum(amount-held-paid_out),0) into amt from v1.allocations where caterer_id=cid;
   if amt<=0 then raise exception 'AMOUNT_INVALID';end if;insert into v1.payouts(caterer_id,amount) values(cid,amt) returning id into ident;
   insert into v1.payout_items select ident,id,amount-held-paid_out from v1.allocations where caterer_id=cid and amount-held-paid_out>0;
   update v1.allocations set paid_out=amount-held where caterer_id=cid;insert into v1.outbox(kind,payload,dedupe) values('payout.create',jsonb_build_object('payoutId',ident),ident::text);r:=jsonb_build_object('id',ident);
  end if;
 elsif action='notification.read' then update v1.notifications set read_at=now() where user_id=u and id=(a->>'id')::uuid;
 elsif action='device.register' then insert into v1.devices(user_id,token) values(u,a->>'token') on conflict(token) do update set user_id=u;
 elsif action='invite.accept' then
  select caterer_id into cid from v1.invites where code=a->>'code' and role='staff' and used_by is null for update;if not found then raise exception 'NOT_FOUND';end if;
  insert into v1.staff values(cid,u,'staff') on conflict do nothing;update v1.invites set used_by=u where code=a->>'code';update v1.profiles set role='staff' where id=u and role='customer';
 else raise exception 'INVALID_ACTION';end if;
 insert into v1.audit(actor_id,action,details) values(u,action,jsonb_build_object('id',coalesce(r->>'id',a->>'id'),'requestId',request_id,'reason',coalesce(a->>'reason',a->>'response'),'dateBefore',d.service_date,'dateAfter',a->>'date','versionBefore',d.version,'amount',a->>'amount','status',a->>'status','catererId',coalesce(cid,p.caterer_id),'customerId',s.user_id));
 insert into v1.receipts values(u,request_id,hash,r);return r;
end $$;$command$;
 end if;
end $install$;
create or replace function public.catera_v1_read(resource text,params jsonb default '{}') returns jsonb language plpgsql security definer set search_path='' as $$
declare u uuid:=auth.uid();result jsonb;seller_id uuid;dt date;lim int:=least(greatest(coalesce((params->>'limit')::int,50),1),100);offst int:=greatest(coalesce((params->>'offset')::int,0),0);
begin
 if resource='catalog' then
  select jsonb_build_object('items',coalesce(jsonb_agg(x.o),'[]'),'nextCursor',case when count(*)=lim then (offst+lim)::text else null end) into result from (select v1.offer(p) o from v1.packages p join v1.caterers c on c.id=p.caterer_id where p.status='published' and c.status='approved' order by case when c.areas @> array[params->>'area'] then 0 else 1 end,p.slug limit lim offset offst)x;return result;
 elsif resource='reviews' then return coalesce((select jsonb_agg(to_jsonb(r)||jsonb_build_object('customer',p.name)) from v1.reviews r join v1.profiles p on p.id=r.user_id where r.package_id=(params->>'id')::uuid and not hidden),'[]');
 end if;
 if u is null then raise exception 'UNAUTHORIZED';end if;
 if resource='actor' then return (select to_jsonb(p)||jsonb_build_object('catererId',(select caterer_id from v1.staff where user_id=u limit 1)) from v1.profiles p where p.id=u);
 elsif resource='menu-month' then return v1.menu_month(u,params);
 elsif resource='availability' then return v1.availability(u,params);
 elsif resource='quote' then return v1.quote(u,params);
 elsif resource='checkout' then return (select to_jsonb(x) from v1.checkouts x where id=(params->>'id')::uuid and user_id=u);
 elsif resource='customer' then
  return (case when params->>'calendarMeta'='true' then jsonb_build_object('calendarMeta',(
    select jsonb_build_object('nextDeliveryDate',min(d.service_date),'lastUpcomingDeliveryDate',max(d.service_date))
    from v1.delivery_days d join v1.subscriptions s on s.id=d.subscription_id
    where s.user_id=u and d.service_date >= (current_timestamp at time zone 'Asia/Jakarta')::date
      and d.status not in ('delivered','cancelled')
      and exists (select 1 from v1.fulfillments f where f.day_id=d.id and f.status not in ('delivered','cancelled'))
  )) else '{}'::jsonb end) || jsonb_build_object('subscriptions',coalesce((select jsonb_agg(to_jsonb(s)||jsonb_build_object('remaining',(select count(*) from v1.delivery_days d where d.subscription_id=s.id and d.status not in('delivered','cancelled')))) from v1.subscriptions s where s.user_id=u),'[]'),'deliveries',coalesce((select jsonb_agg(v1.delivery(d) order by d.service_date) from v1.delivery_days d join v1.subscriptions s on s.id=d.subscription_id where s.user_id=u and ((params->>'deliveryId' is not null and d.id=(params->>'deliveryId')::uuid) or (params->>'deliveryId' is null and d.service_date between coalesce((params->>'from')::date,current_date-7) and coalesce((params->>'to')::date,current_date+60)))),'[]'),'addresses',coalesce((select jsonb_agg(to_jsonb(a)-'user_id') from v1.addresses a where user_id=u),'[]'),'notifications',coalesce((select jsonb_agg(to_jsonb(n)) from (select * from v1.notifications where user_id=u order by created_at desc limit 50)n),'[]'),'cases',coalesce((select jsonb_agg(to_jsonb(s)) from v1.support_cases s where user_id=u),'[]'));
 elsif resource='conversations' then
  return coalesce((select jsonb_agg(to_jsonb(c)||jsonb_build_object('caterer',k.name,'customer',p.name,'messages',coalesce((select jsonb_agg(to_jsonb(m) order by m.created_at) from (select * from v1.messages where conversation_id=c.id order by created_at desc limit 100)m),'[]'))) from v1.conversations c join v1.caterers k on k.id=c.caterer_id join v1.profiles p on p.id=c.customer_id where c.customer_id=u or v1.is_staff(u,c.caterer_id)),'[]');
 elsif resource='seller' then
  seller_id:=(params->>'id')::uuid;dt:=coalesce((params->>'date')::date,current_date);if not v1.is_staff(u,seller_id) then raise exception 'FORBIDDEN';end if;
  return jsonb_build_object('caterer',(select to_jsonb(k)||jsonb_build_object('area',k.areas) from v1.caterers k where id=seller_id),'offers',coalesce((select jsonb_agg(v1.offer(p)) from v1.packages p where caterer_id=seller_id),'[]'),'dishes',coalesce((select jsonb_agg(v1.library_dish(d) order by d.details->>'name',d.id) from v1.dishes d where d.caterer_id=seller_id),'[]'),'categories',v1.categories(seller_id),'contentRevisions',v1.seller_content_revisions(seller_id),'datedMenus',coalesce((select jsonb_agg(to_jsonb(m)) from v1.menus m join v1.packages p on p.id=m.package_id where p.caterer_id=seller_id and m.service_date=dt),'[]'),'deliveries',coalesce((select jsonb_agg(v1.delivery(d)) from v1.delivery_days d join v1.subscriptions s on s.id=d.subscription_id join v1.packages p on p.id=s.package_id where p.caterer_id=seller_id and d.service_date=dt),'[]'),'cases',coalesce((select jsonb_agg(to_jsonb(x)) from v1.support_cases x where caterer_id=seller_id),'[]'),'customers',coalesce((select jsonb_agg(jsonb_build_object('id',p.id,'name',p.name,'source',r.source)) from v1.relationships r join v1.profiles p on p.id=r.user_id where r.caterer_id=seller_id),'[]'),'transactions',case when v1.is_staff(u,seller_id,true) then coalesce((select jsonb_agg(to_jsonb(x)) from (select ch.* from v1.checkouts ch join v1.packages p on p.id=ch.package_id where p.caterer_id=seller_id order by created_at desc limit 100)x),'[]') else '[]'::jsonb end,'staff',case when v1.is_staff(u,seller_id,true) then coalesce((select jsonb_agg(to_jsonb(s)||jsonb_build_object('name',p.name)) from v1.staff s join v1.profiles p on p.id=s.user_id where s.caterer_id=seller_id),'[]') else '[]'::jsonb end,'payouts',case when v1.is_staff(u,seller_id,true) then coalesce((select jsonb_agg(to_jsonb(p)) from v1.payouts p where caterer_id=seller_id),'[]') else '[]'::jsonb end);
 elsif resource='admin' then
  if not v1.is_admin(u) then raise exception 'FORBIDDEN';end if;
  return jsonb_build_object('caterers',coalesce((select jsonb_agg(to_jsonb(c)||jsonb_build_object('area',c.areas,'offers',coalesce((select jsonb_agg(v1.offer(pack)) from v1.packages pack where pack.caterer_id=c.id),'[]'))) from v1.caterers c),'[]'),'cases',coalesce((select jsonb_agg(to_jsonb(s)) from v1.support_cases s),'[]'),'transactions',coalesce((select jsonb_agg(to_jsonb(c)) from (select * from v1.checkouts order by created_at desc limit 100)c),'[]'),'audit',coalesce((select jsonb_agg(to_jsonb(a)) from (select * from v1.audit order by created_at desc limit 100)a),'[]'),'promotions',coalesce((select jsonb_agg(to_jsonb(p)) from v1.promotions p),'[]'),'payouts',coalesce((select jsonb_agg(to_jsonb(p)) from v1.payouts p),'[]'),'refunds',coalesce((select jsonb_agg(to_jsonb(r)) from v1.refunds r),'[]'),'reviews',coalesce((select jsonb_agg(to_jsonb(r)) from v1.reviews r),'[]'));
 end if;raise exception 'NOT_FOUND';
end $$;
revoke all on all functions in schema v1 from public,anon,authenticated;
