-- Generated by compile-dishes-migration.mjs; prior migrations and snapshots are preserved.
-- Reusable defaults only. Embedded package and purchase values stay authoritative.
create table v1.dishes (
 id uuid primary key default gen_random_uuid(), caterer_id uuid not null references v1.caterers,
 details jsonb not null, version int not null default 1 check(version>0), archived boolean not null default false,
 created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create index dishes_caterer on v1.dishes(caterer_id,archived);
alter table v1.dishes enable row level security;
create function v1.library_dish(d v1.dishes) returns jsonb language sql stable set search_path='' as $$
 select d.details||jsonb_build_object('id',d.id,'catererId',d.caterer_id,'version',d.version,'archived',d.archived)
$$;
create function v1.valid_dish(d jsonb) returns boolean language plpgsql immutable set search_path='' as $$
begin
 return coalesce(jsonb_typeof(d)='object' and jsonb_typeof(d->'name')='string' and length(trim(d->>'name')) between 1 and 120
 and jsonb_typeof(d->'description')='string' and length(d->>'description')<=600
 and jsonb_typeof(d->'image')='string' and length(d->>'image')<=500
 and jsonb_typeof(d->'serving')='string' and length(d->>'serving')<=100,false);
end $$;
alter table v1.dishes add constraint valid_dish_details check(v1.valid_dish(details));
create function v1.check_dish_sources(cid uuid,menus jsonb,previous jsonb default '[]') returns void language plpgsql set search_path='' as $$
declare m jsonb;i jsonb;d v1.dishes;
begin
 for m in select * from jsonb_array_elements(menus) loop
  for i in select * from jsonb_array_elements(coalesce(m->'items','[]')) loop
   if i ? 'sourceDishId' or i ? 'sourceDishVersion' or i ? 'sourceServing' then
    if jsonb_typeof(i->'sourceDishId') is distinct from 'string' or jsonb_typeof(i->'sourceDishVersion') is distinct from 'number'
     or (i->>'sourceDishVersion')::numeric<>trunc((i->>'sourceDishVersion')::numeric) or (i->>'sourceDishVersion')::numeric<1
     or (i ? 'sourceServing' and (jsonb_typeof(i->'sourceServing')<>'string' or length(i->>'sourceServing')>100)) then raise exception 'INVALID_INPUT';end if;
    select * into d from v1.dishes where id=(i->>'sourceDishId')::uuid and caterer_id=cid for share;
    if not found then raise exception 'FORBIDDEN';end if;
    if (i->>'sourceDishVersion')::numeric>d.version then raise exception 'CONFLICT';end if;
    if d.archived and not exists(select 1 from jsonb_array_elements(coalesce(previous,'[]')) pm cross join lateral jsonb_array_elements(coalesce(pm->'items','[]')) pi where pi->>'id'=i->>'id' and pi->>'sourceDishId'=i->>'sourceDishId' and pi->>'sourceDishVersion'=i->>'sourceDishVersion') then raise exception 'INVALID_INPUT';end if;
   end if;
  end loop;
 end loop;
end $$;

create or replace function v1.valid_offer(o jsonb) returns boolean language plpgsql immutable set search_path='' as $$
declare w jsonb;t jsonb;k text;lo int;complete boolean;
begin
 if o is null or jsonb_typeof(o)<>'object' or not(o ?& array['name','description','price','days','meal','flexible','weekdays','status','capacity','tiers','menus','image','windows','tags','trialPrice','trialMax']) then return false;end if;
 complete:=o->>'status'<>'draft';
 if o->>'status' not in('draft','published','paused','retired') or o->>'meal' not in('lunch','dinner','both') or jsonb_typeof(o->'flexible')<>'boolean' then return false;end if;
 foreach k in array array['name','description','image'] loop
  if jsonb_typeof(o->k)<>'string' then return false;end if;
  lo:=case k when 'name' then 3 when 'description' then 10 else 1 end;
  if (complete or length(trim(o->>k))>0) and length(trim(o->>k))<lo then return false;end if;
  if length(o->>k)>(case k when 'name' then 100 when 'description' then 1500 else 500 end) then return false;end if;
 end loop;
 foreach k in array array['price','days'] loop
  if jsonb_typeof(o->k)<>'number' or (o->>k)::numeric<>trunc((o->>k)::numeric) or (o->>k)::numeric not between (case k when 'price' then 1000 else 1 end) and (case k when 'price' then 10000000 else 60 end) then return false;end if;
 end loop;
 foreach k in array array['trialPrice','trialMax'] loop
  if o->k<>'null'::jsonb and (jsonb_typeof(o->k)<>'number' or (o->>k)::numeric<>trunc((o->>k)::numeric) or (o->>k)::numeric<(case k when 'trialPrice' then 1000 else 1 end)) then return false;end if;
 end loop;
 if jsonb_typeof(o->'windows')<>'object' or jsonb_typeof(o->'windows'->'lunch') is distinct from 'string' or jsonb_typeof(o->'windows'->'dinner') is distinct from 'string' or length(o->'windows'->>'lunch')<3 or length(o->'windows'->>'dinner')<3 then return false;end if;
 if jsonb_typeof(o->'capacity')<>'object' or jsonb_typeof(o->'weekdays')<>'array' or jsonb_array_length(o->'weekdays') not between (case when complete then 1 else 0 end) and 7 then return false;end if;
 for w in select value from jsonb_each(o->'capacity') loop
  if jsonb_typeof(w)<>'number' or w::text::numeric<0 or w::text::numeric<>trunc(w::text::numeric) then return false;end if;
 end loop;
 for w in select * from jsonb_array_elements(o->'weekdays') loop
  if jsonb_typeof(w)<>'number' or w::text::numeric not between 0 and 6 or w::text::numeric<>trunc(w::text::numeric) or not(o->'capacity' ? w::text) then return false;end if;
 end loop;
 if jsonb_typeof(o->'tiers')<>'array' or jsonb_typeof(o->'tags')<>'array' or jsonb_typeof(o->'menus')<>'array' or jsonb_array_length(o->'menus')>2 then return false;end if;
 for t in select * from jsonb_array_elements(o->'tiers') loop
  if jsonb_typeof(t->'min') is distinct from 'number' or (t->>'min')::numeric<1 or (t->>'min')::numeric<>trunc((t->>'min')::numeric) or jsonb_typeof(t->'percent') is distinct from 'number' or (t->>'percent')::numeric not between 0 and 90 then return false;end if;
 end loop;
 for t in select * from jsonb_array_elements(o->'tags') loop if jsonb_typeof(t)<>'string' or length(t#>>'{}')>40 then return false;end if;end loop;
 return coalesce(v1.valid_contents(o,complete),false);
 exception when others then return false;
end $$;

create or replace function public.catera_v1_command(action text,payload jsonb,request_id uuid) returns jsonb language plpgsql security definer set search_path='' as $$
declare u uuid:=auth.uid();a jsonb:=payload;r jsonb:='{}';old v1.receipts;hash text:=md5(action||payload::text);p v1.packages;o jsonb;c v1.checkouts;s v1.subscriptions;d v1.delivery_days;ad v1.addresses;cs v1.support_cases;ident uuid;cid uuid;target date;qty int;amt int;nextstatus text;mealstatus text;mealkey text;dt text;rowdata jsonb;rev int;dish v1.dishes;
begin
 if u is null then raise exception 'UNAUTHORIZED';end if;
 perform pg_advisory_xact_lock(hashtext(u::text));
 select * into old from v1.receipts where actor_id=u and receipts.request_id=catera_v1_command.request_id;
 if found then if old.hash<>hash then raise exception 'CONFLICT';end if;return old.result;end if;
 if action='profile.ensure' then insert into v1.profiles(id,name) values(u,coalesce(nullif(a->>'name',''),'Pelanggan')) on conflict do nothing;r:=jsonb_build_object('id',u);
 elsif action='address.save' then
  if length(a->>'line')<5 or coalesce(a->>'area','')='' then raise exception 'INVALID_INPUT';end if;
  ident:=(a->>'id')::uuid;
  if ident is null then insert into v1.addresses(user_id,label,line,area,city,instructions) values(u,a->>'label',a->>'line',a->>'area',a->>'city',coalesce(a->>'instructions','')) returning id into ident;
  else update v1.addresses set label=a->>'label',line=a->>'line',area=a->>'area',city=a->>'city',instructions=coalesce(a->>'instructions',''),version=version+1 where id=ident and user_id=u and version=(a->>'version')::int;if not found then raise exception 'CONFLICT';end if;end if;r:=jsonb_build_object('id',ident);
 elsif action='checkout.create' then
  select * into p from v1.packages where id=(a->>'packageId')::uuid for update;o:=v1.quote(u,a);if a ? 'expectedQuote' and a->'expectedQuote'<>o then raise exception 'PRICE_CHANGED';end if;
  insert into v1.checkouts(user_id,package_id,address_id,quote,expires_at) values(u,p.id,(a->>'addressId')::uuid,o,least(clock_timestamp()+interval '15 minutes',v1.cutoff(o->'offer',(o->'dates'->>0)::date))) returning * into c;
  for dt in select jsonb_array_elements_text(o->'dates') loop insert into v1.reservations values(c.id,p.id,dt::date,(a->>'portions')::int,'held');end loop;
  insert into v1.relationships values(u,p.caterer_id,o->>'source') on conflict do nothing;
  update v1.invites set used_by=u where code=a->>'invite' and caterer_id=p.caterer_id and role='customer' and used_by is null;
  insert into v1.outbox(kind,payload,dedupe) values('payment.create',jsonb_build_object('checkoutId',c.id),c.id::text);
  r:=to_jsonb(c);
 elsif action='checkout.demo_pay' then
  if coalesce(current_setting('catera.demo',true),'false')<>'true' then raise exception 'FORBIDDEN';end if;
  select * into c from v1.checkouts where id=(a->>'id')::uuid and user_id=u for update;if not found then raise exception 'FORBIDDEN';end if;
  insert into v1.payments(checkout_id,provider_id,amount,state) values(c.id,'demo-'||c.id,(c.quote->>'total')::int,'paid') on conflict(checkout_id) do nothing;
  ident:=v1.activate(c.id);r:=jsonb_build_object('id',c.id,'subscriptionId',ident);
 elsif action in('delivery.reschedule','delivery.address','delivery.status') then
  select * into d from v1.delivery_days where id=(a->>'id')::uuid;if not found then raise exception 'NOT_FOUND';end if;select * into s from v1.subscriptions where id=d.subscription_id;select * into p from v1.packages where id=s.package_id for update;
  select * into d from v1.delivery_days where id=d.id for update;
  if s.user_id<>u and not v1.is_staff(u,p.caterer_id) then raise exception 'FORBIDDEN';end if;
  if d.version is distinct from (a->>'version')::int then raise exception 'CONFLICT';end if;
  if action='delivery.status' then
   if not v1.is_staff(u,p.caterer_id) then raise exception 'FORBIDDEN';end if;if d.service_date>(clock_timestamp() at time zone (s.snapshot->'offer'->>'timezone'))::date then raise exception 'INVALID_DATE';end if;nextstatus:=a->>'status';
   mealkey:=a->>'meal';if mealkey is null then if (select count(*) from v1.fulfillments where day_id=d.id)>1 then raise exception 'INVALID_INPUT';end if;select meal into mealkey from v1.fulfillments where day_id=d.id;end if;
   select status into mealstatus from v1.fulfillments where day_id=d.id and meal=mealkey;if not found then raise exception 'INVALID_INPUT';end if;
   if not ((mealstatus='scheduled' and nextstatus='preparing') or (mealstatus='preparing' and nextstatus='out_for_delivery') or (mealstatus='out_for_delivery' and nextstatus in('delivered','issue')) or (mealstatus='issue' and nextstatus='out_for_delivery')) then raise exception 'INVALID_STATE';end if;
   update v1.fulfillments set status=nextstatus where day_id=d.id and meal=mealkey;
   if not exists(select 1 from v1.fulfillments where day_id=d.id and status<>'delivered') then nextstatus:='delivered';elsif exists(select 1 from v1.fulfillments where day_id=d.id and status='issue') then nextstatus:='issue';elsif exists(select 1 from v1.fulfillments where day_id=d.id and status='out_for_delivery') then nextstatus:='out_for_delivery';else nextstatus:='preparing';end if;
   update v1.delivery_days set status=nextstatus,version=version+1 where id=d.id;
   if not exists(select 1 from v1.delivery_days where subscription_id=s.id and status not in('delivered','cancelled')) then update v1.subscriptions set status='completed' where id=s.id;end if;
   perform v1.notify(s.user_id,'delivery',case when nextstatus='delivered' then 'Makanan sudah terkirim. Selamat menikmati!' else 'Status pengantaran Anda diperbarui.' end,'/deliveries/'||d.id);
  else
   if d.status<>'scheduled' or v1.cutoff(s.snapshot->'offer',d.service_date)<=clock_timestamp() then raise exception 'CUTOFF';end if;
   if action='delivery.address' then
    select * into ad from v1.addresses where id=(a->>'addressId')::uuid and user_id=s.user_id;if not found then raise exception 'FORBIDDEN';end if;
    if not (v1.offer(p)->'areas' ? ad.area) then raise exception 'COVERAGE';end if;
    update v1.delivery_days set address=to_jsonb(ad)-'user_id',version=version+1 where id=d.id;
   else
    if not (s.snapshot->'offer'->>'flexible')::boolean then raise exception 'FIXED_PACKAGE';end if;target:=(a->>'date')::date;
    if v1.cutoff(s.snapshot->'offer',target)<=clock_timestamp() then raise exception 'CUTOFF';end if;
    if not(s.snapshot->'offer'->'weekdays' @> to_jsonb(extract(dow from target)::int)) then raise exception 'INVALID_DATE';end if;
    if exists(select 1 from v1.delivery_days where subscription_id=s.id and service_date=target) then raise exception 'DUPLICATE_DATE';end if;
    if v1.slots(p.id,target)-v1.demand(p.id,target)<s.portions then raise exception 'CAPACITY';end if;
    if exists(select 1 from v1.subscriptions x where x.user_id=s.user_id and x.package_id=p.id and x.id<>s.id and x.status='active' and x.starts_on<=greatest(s.ends_on,target) and x.ends_on>=least(s.starts_on,target)) then raise exception 'OVERLAP';end if;
    if exists(select 1 from v1.checkouts pending where pending.user_id=s.user_id and pending.package_id=p.id and pending.id<>s.checkout_id and pending.state='pending' and pending.expires_at>clock_timestamp() and (pending.quote->'dates'->>0)::date<=greatest(s.ends_on,target) and (pending.quote->'dates'->>-1)::date>=least(s.starts_on,target)) then raise exception 'OVERLAP';end if;
    insert into v1.reservations(checkout_id,package_id,service_date,portions,state) values(s.checkout_id,p.id,target,s.portions,'confirmed') on conflict(checkout_id,service_date) do update set portions=excluded.portions,state='confirmed';
    update v1.reservations set state='released' where checkout_id=s.checkout_id and service_date=d.service_date;
    update v1.delivery_days set service_date=target,version=version+1 where id=d.id;
    update v1.subscriptions set starts_on=(select min(service_date) from v1.delivery_days where subscription_id=s.id),ends_on=(select max(service_date) from v1.delivery_days where subscription_id=s.id) where id=s.id;
   end if;perform v1.notify(s.user_id,'change','Perubahan pengantaran sudah tersimpan.','/deliveries/'||d.id);
  end if;r:=jsonb_build_object('id',d.id);
 elsif action='support.create' then
  if a->>'deliveryId' is not null then select * into d from v1.delivery_days where id=(a->>'deliveryId')::uuid;select * into s from v1.subscriptions where id=d.subscription_id;else select * into s from v1.subscriptions where id=(a->>'subscriptionId')::uuid;end if;
  if s.user_id is distinct from u then raise exception 'FORBIDDEN';end if;select * into p from v1.packages where id=s.package_id;
  insert into v1.support_cases(user_id,caterer_id,delivery_id,subscription_id,checkout_id,subject,description) values(u,p.caterer_id,d.id,s.id,s.checkout_id,a->>'subject',a->>'description') returning id into ident;
  update v1.allocations set held=greatest(held,amount-paid_out) where checkout_id=s.checkout_id;
  perform v1.notify(st.user_id,'support','Ada permintaan bantuan baru.','/seller/support') from v1.staff st where st.caterer_id=p.caterer_id;r:=jsonb_build_object('id',ident);
 elsif action in('support.respond','support.escalate','support.resolve') then
  select * into cs from v1.support_cases where id=(a->>'id')::uuid for update;if not found then raise exception 'NOT_FOUND';end if;
  if cs.status='resolved' then raise exception 'CONFLICT';end if;
  if action='support.respond' then if not v1.is_staff(u,cs.caterer_id) then raise exception 'FORBIDDEN';end if;update v1.support_cases set status='responded',resolution=a->>'response' where id=cs.id;
  elsif action='support.escalate' then if cs.user_id<>u and not v1.is_staff(u,cs.caterer_id) then raise exception 'FORBIDDEN';end if;update v1.support_cases set status='escalated' where id=cs.id;
  else
   if not v1.is_admin(u) then raise exception 'FORBIDDEN';end if;if cs.status='resolved' then raise exception 'CONFLICT';end if;if coalesce(length(a->>'reason'),0)<5 then raise exception 'INVALID_INPUT';end if;
   select * into c from v1.checkouts where id=cs.checkout_id for update;amt:=coalesce((a->>'amount')::int,0);
   if amt<0 or amt>(c.quote->>'total')::int-coalesce((select sum(amount) from v1.refunds where checkout_id=c.id and state<>'failed'),0) then raise exception 'AMOUNT_INVALID';end if;
   if amt>0 then insert into v1.refunds(case_id,checkout_id,amount) values(cs.id,c.id,amt) returning id into ident;insert into v1.outbox(kind,payload,dedupe) values('refund.create',jsonb_build_object('refundId',ident),ident::text);end if;
   if coalesce((a->>'cancelRemaining')::boolean,false) then
    select * into p from v1.packages where id=c.package_id for update;
    update v1.reservations set state='released' where checkout_id=c.id and service_date in(select service_date from v1.delivery_days where subscription_id=c.subscription_id and status in('scheduled','preparing','issue'));
    update v1.fulfillments set status='cancelled' where day_id in(select id from v1.delivery_days where subscription_id=c.subscription_id and status in('scheduled','preparing','issue'));
    update v1.delivery_days set status='cancelled',version=version+1 where subscription_id=c.subscription_id and status in('scheduled','preparing','issue');update v1.subscriptions set status='cancelled' where id=c.subscription_id;
   end if;
   update v1.support_cases set status='resolved',resolution=a->>'reason',amount=amt where id=cs.id;
   if amt=0 and not exists(select 1 from v1.support_cases where checkout_id=c.id and status<>'resolved') then update v1.allocations set held=0 where checkout_id=c.id;end if;
  end if;perform v1.notify(cs.user_id,'support','Permintaan bantuan Anda diperbarui.','/support');r:=jsonb_build_object('id',cs.id);
 elsif action='message.send' then
  cid:=(a->>'catererId')::uuid;ident:=(a->>'conversationId')::uuid;
  if ident is null then if not exists(select 1 from v1.caterers where id=cid and status='approved') then raise exception 'NOT_FOUND';end if;insert into v1.conversations(customer_id,caterer_id) values(u,cid) on conflict(customer_id,caterer_id) do update set customer_id=excluded.customer_id returning id into ident;
  else if not exists(select 1 from v1.conversations where id=ident and (customer_id=u or v1.is_staff(u,caterer_id))) then raise exception 'FORBIDDEN';end if;end if;
  insert into v1.messages(conversation_id,sender_id,body) values(ident,u,trim(a->>'body'));
  perform v1.notify(v.customer_id,'message','Pesan baru dari katerer.','/messages') from v1.conversations v where v.id=ident and v.customer_id<>u;
  perform v1.notify(st.user_id,'message','Pesan baru dari pelanggan.','/seller/support') from v1.staff st join v1.conversations v on v.caterer_id=st.caterer_id where v.id=ident and v.customer_id=u;
  r:=jsonb_build_object('id',ident);
 elsif action='review.save' then
  select * into s from v1.subscriptions where id=(a->>'subscriptionId')::uuid and user_id=u;if not found or not exists(select 1 from v1.delivery_days where subscription_id=s.id and status='delivered') then raise exception 'FORBIDDEN';end if;
  insert into v1.reviews(subscription_id,user_id,package_id,rating,food,delivery,value,body) values(s.id,u,s.package_id,(a->>'rating')::int,(a->>'food')::int,(a->>'delivery')::int,(a->>'value')::int,a->>'body') on conflict(subscription_id) do update set rating=excluded.rating,food=excluded.food,delivery=excluded.delivery,value=excluded.value,body=excluded.body returning id into ident;r:=jsonb_build_object('id',ident);
 elsif action='review.reply' then
  if not exists(select 1 from v1.reviews review join v1.packages pack on pack.id=review.package_id where review.id=(a->>'id')::uuid and v1.is_staff(u,pack.caterer_id)) then raise exception 'FORBIDDEN';end if;update v1.reviews set reply=a->>'reply' where id=(a->>'id')::uuid;
 elsif action='seller.create' then
  insert into v1.caterers(slug,name,description,areas) values(a->>'slug',a->>'name',a->>'description',array(select jsonb_array_elements_text(a->'areas'))) returning id into ident;insert into v1.staff values(ident,u,'owner');update v1.profiles set role='owner' where id=u;r:=jsonb_build_object('id',ident);
 elsif action in('dish.save','dish.archive','seller.save','seller.submit','staff.invite','package.save','capacity.save','menu.save','production.freeze','import.preview','import.commit') then
  cid:=(a->>'catererId')::uuid;if not v1.is_staff(u,cid,action<>'production.freeze') then raise exception 'FORBIDDEN';end if;
  if action='seller.save' then update v1.caterers set name=a->>'name',description=a->>'description',areas=array(select jsonb_array_elements_text(a->'areas')),cutoff=(a->>'cutoff')::time,version=version+1 where id=cid and version=(a->>'version')::int;if not found then raise exception 'CONFLICT';end if;
  elsif action='seller.submit' then if not exists(select 1 from v1.packages where caterer_id=cid) then raise exception 'INVALID_INPUT';end if;update v1.caterers set status='submitted',version=version+1 where id=cid and status in('draft','corrections');if not found then raise exception 'CONFLICT';end if;
  elsif action='staff.invite' then insert into v1.invites(caterer_id,role) values(cid,'staff') returning id into ident;r:=(select to_jsonb(i) from v1.invites i where id=ident);
  elsif action in('dish.save','dish.archive') then
   ident:=(a->>'id')::uuid;
   if ident is not null then
    select * into dish from v1.dishes where id=ident and caterer_id=cid for update;
    if not found then raise exception 'FORBIDDEN';end if;
    if jsonb_typeof(a->'version') is distinct from 'number' or (a->>'version')::numeric<>dish.version then raise exception 'CONFLICT';end if;
   end if;
   if action='dish.save' then
    if not v1.valid_dish(a->'details') then raise exception 'INVALID_INPUT';end if;
    if ident is null then insert into v1.dishes(caterer_id,details) values(cid,a->'details') returning * into dish;
    else update v1.dishes set details=a->'details',version=version+1,updated_at=now() where id=ident returning * into dish;end if;
   else
    if ident is null or jsonb_typeof(a->'archived') is distinct from 'boolean' then raise exception 'INVALID_INPUT';end if;
    update v1.dishes set archived=(a->>'archived')::boolean,version=version+1,updated_at=now() where id=ident returning * into dish;
   end if;
   ident:=dish.id;r:=v1.library_dish(dish);
  elsif action='package.save' then
   if not v1.valid_offer(a->'offer') then raise exception 'INVALID_INPUT';end if;
   ident:=(a->>'id')::uuid;
   if ident is not null then select * into p from v1.packages where id=ident and caterer_id=cid for update;if not found then raise exception 'FORBIDDEN';end if;end if;
   if coalesce(a->'offer'->>'packageType','')='' and a->'offer'->>'status'<>'draft' and (ident is null or coalesce((p.offer->>'contentRevision')::int,0)>0 or v1.contents_template(a->'offer') is distinct from v1.contents_template(p.offer)) then raise exception 'CLASSIFY_PACKAGE';end if;
   perform v1.check_dish_sources(cid,a->'offer'->'menus',p.offer->'menus');
   o:=(a->'offer')-'contentRevision';
   if coalesce(o->>'packageType','')<>'' then
    o:=jsonb_set(o,'{menus}',(select coalesce(jsonb_agg((m-'source')||jsonb_build_object('name',v1.contents_summary(m))),'[]') from jsonb_array_elements(o->'menus') m));
   end if;
   rev:=case when ident is null then 1 when v1.contents_template(o)=v1.contents_template(p.offer) then coalesce((p.offer->>'contentRevision')::int,0) else coalesce((select max(revision) from v1.content_revisions where package_id=ident),0)+1 end;
   a:=jsonb_set(a,'{offer}',o||jsonb_build_object('contentRevision',rev));
   if ident is null then insert into v1.packages(caterer_id,slug,offer,status) values(cid,a->>'slug',a->'offer',a->'offer'->>'status') returning id into ident;
   else select * into p from v1.packages where id=ident and caterer_id=cid for update;if not found then raise exception 'FORBIDDEN';end if;
    for target in select distinct service_date from v1.reservations where package_id=ident and state<>'released' and service_date>=current_date loop
     if not exists(select 1 from v1.capacity where package_id=ident and service_date=target) and coalesce((a->'offer'->'capacity'->>extract(dow from target)::int::text)::int,0)<v1.demand(ident,target) then raise exception 'CAPACITY';end if;
    end loop;
    update v1.packages set offer=a->'offer',status=a->'offer'->>'status',version=version+1 where id=ident and caterer_id=cid and version=(a->>'version')::int;if not found then raise exception 'CONFLICT';end if;
   end if;
   insert into v1.content_revisions(package_id,revision,contents) values(ident,rev,v1.contents_template(a->'offer')) on conflict do nothing;
   r:=jsonb_build_object('id',ident,'contentRevision',rev);
  elsif action='capacity.save' then
   select * into p from v1.packages where id=(a->>'packageId')::uuid and caterer_id=cid for update;if not found then raise exception 'FORBIDDEN';end if;target:=(a->>'date')::date;qty:=(a->>'slots')::int;
   if qty<v1.demand(p.id,target) or (coalesce((a->>'closed')::boolean,false) and v1.demand(p.id,target)>0) then raise exception 'CAPACITY';end if;
   insert into v1.capacity values(p.id,target,qty,coalesce((a->>'closed')::boolean,false)) on conflict(package_id,service_date) do update set slots=excluded.slots,closed=excluded.closed;
  elsif action='menu.save' then
   select * into p from v1.packages where id=(a->>'packageId')::uuid and caterer_id=cid for update;if not found then raise exception 'FORBIDDEN';end if;
   rev:=coalesce((a->>'contentRevision')::int,0);
   select contents into o from v1.content_revisions where package_id=p.id and revision=rev;if not found then raise exception 'INVALID_INPUT';end if;
   if a->>'meal' not in('lunch','dinner') or (o->>'meal'<>'both' and a->>'meal'<>o->>'meal') then raise exception 'INVALID_INPUT';end if;
   perform v1.check_dish_sources(cid,jsonb_build_array(a->'details'),coalesce((select jsonb_build_array(details) from v1.menus where package_id=p.id and content_revision=rev and service_date=(a->>'date')::date and meal=a->>'meal'),o->'menus'));
   rowdata:=a->'details'||jsonb_build_object('meal',a->>'meal');
   if coalesce(o->>'packageType','')<>'' then
    if not v1.valid_contents(jsonb_build_object('packageType',o->'packageType','meal',a->>'meal','menus',jsonb_build_array(rowdata)),true) then raise exception 'INVALID_INPUT';end if;
    if (select x->'composition' from jsonb_array_elements(o->'menus') x where x->>'meal'=a->>'meal') is distinct from rowdata->'composition' then raise exception 'COMPOSITION_CHANGED';end if;
    if o->>'packageType'='ala_carte' and jsonb_array_length(rowdata->'items')<>(select jsonb_array_length(x->'items') from jsonb_array_elements(o->'menus') x where x->>'meal'=a->>'meal') then raise exception 'COMPOSITION_CHANGED';end if;
    rowdata:=rowdata||jsonb_build_object('name',v1.contents_summary(rowdata));
   else
    if jsonb_typeof(rowdata->'name') is distinct from 'string' or length(trim(rowdata->>'name')) not between 1 and 1500 then raise exception 'INVALID_INPUT';end if;
    if rowdata ? 'items' or rowdata ? 'nutrition' or rowdata ? 'composition' then raise exception 'CLASSIFY_PACKAGE';end if;
   end if;
   target:=(a->>'date')::date;
   if target < (clock_timestamp() at time zone (select timezone from v1.caterers where id=cid))::date then raise exception 'CUTOFF';end if;
   if exists(select 1 from v1.delivery_days day join v1.subscriptions sub on sub.id=day.subscription_id join v1.fulfillments f on f.day_id=day.id where sub.package_id=p.id and coalesce((sub.snapshot->'offer'->>'contentRevision')::int,0)=rev and day.service_date=target and f.meal=a->>'meal' and f.status='delivered') then raise exception 'CUTOFF';end if;
   select version into qty from v1.menus where package_id=p.id and content_revision=rev and service_date=target and meal=a->>'meal';
   if coalesce(qty,0)<>coalesce((a->>'version')::int,0) then raise exception 'CONFLICT';end if;
   insert into v1.menus(package_id,content_revision,service_date,meal,details,version) values(p.id,rev,target,a->>'meal',rowdata,1)
    on conflict(package_id,content_revision,service_date,meal) do update set details=excluded.details,version=v1.menus.version+1;
   perform v1.notify(sub.user_id,'menu','Menu pengantaran Anda diperbarui.','/calendar') from v1.subscriptions sub join v1.delivery_days day on day.subscription_id=sub.id where sub.package_id=p.id and coalesce((sub.snapshot->'offer'->>'contentRevision')::int,0)=rev and day.service_date=target and day.status not in('delivered','cancelled');
  elsif action='production.freeze' then
   perform 1 from v1.caterers where id=cid for update;target:=(a->>'date')::date;select coalesce(max(revision),0)+1 into rev from v1.production where caterer_id=cid and service_date=target;
   insert into v1.production(caterer_id,service_date,revision,entries) values(cid,target,rev,coalesce((select jsonb_agg(v1.delivery(day)) from v1.delivery_days day join v1.subscriptions sub on sub.id=day.subscription_id join v1.packages pack on pack.id=sub.package_id where pack.caterer_id=cid and day.service_date=target and day.status<>'cancelled'),'[]')) returning id into ident;r:=jsonb_build_object('id',ident,'revision',rev);
  elsif action='import.preview' then
   if jsonb_array_length(a->'rows')>100 then raise exception 'INVALID_INPUT';end if;
   o:='[]';for rowdata in select * from jsonb_array_elements(a->'rows') loop
    if not exists(select 1 from v1.packages where id=(rowdata->>'packageId')::uuid and caterer_id=cid) or not exists(select 1 from v1.profiles where id=(rowdata->>'customerId')::uuid) then raise exception 'INVALID_INPUT';end if;
    r:=v1.import_quote((rowdata->>'customerId')::uuid,rowdata);o:=o||jsonb_build_object('customerId',rowdata->>'customerId','addressId',rowdata->>'addressId','packageId',rowdata->>'packageId','portions',rowdata->'portions','startDate',rowdata->>'startDate','remainingDays',rowdata->'remainingDays','externalReference',rowdata->>'externalReference','preview',r);
   end loop;insert into v1.imports(caterer_id,created_by,rows) values(cid,u,o) returning id into ident;r:=jsonb_build_object('id',ident,'rows',o);
  else
   select rows into o from v1.imports where id=(a->>'id')::uuid and caterer_id=cid and state='preview' for update;if not found then raise exception 'CONFLICT';end if;
   perform 1 from v1.packages where id in(select (j->>'packageId')::uuid from jsonb_array_elements(o) j) order by id for update;
   for rowdata in select * from jsonb_array_elements(o) loop
    select * into p from v1.packages where id=(rowdata->>'packageId')::uuid for update;
    insert into v1.relationships values((rowdata->>'customerId')::uuid,cid,'legacy') on conflict do nothing;
    rowdata:=rowdata||jsonb_build_object('trial',false,'promo','','invite','');
    r:=v1.import_quote((rowdata->>'customerId')::uuid,rowdata);
    insert into v1.checkouts(user_id,package_id,address_id,quote,expires_at) values((rowdata->>'customerId')::uuid,p.id,(rowdata->>'addressId')::uuid,r,now()+interval '15 minutes') returning id into ident;
    for dt in select jsonb_array_elements_text(r->'dates') loop insert into v1.reservations values(ident,p.id,dt::date,(r->>'portions')::int,'held');end loop;
    ident:=v1.activate(ident);update v1.subscriptions set legacy=true where id=ident;delete from v1.allocations where checkout_id=(select checkout_id from v1.subscriptions where id=ident);
   end loop;update v1.imports set state='committed' where id=(a->>'id')::uuid;r:=jsonb_build_object('id',a->>'id');
  end if;
 elsif action in('admin.verify','promotion.save','review.moderate','payout.approve') then
  if not v1.is_admin(u) then raise exception 'FORBIDDEN';end if;
  if action in('admin.verify','review.moderate','payout.approve') and coalesce(length(a->>'reason'),0)<5 then raise exception 'INVALID_INPUT';end if;
  if action='admin.verify' then update v1.caterers set status=a->>'status',review_note=a->>'reason',version=version+1 where id=(a->>'id')::uuid and version=(a->>'version')::int;if not found then raise exception 'CONFLICT';end if;
  elsif action='promotion.save' then insert into v1.promotions(code,percent,active) values(upper(a->>'code'),(a->>'percent')::int,(a->>'active')::boolean) on conflict(code) do update set percent=excluded.percent,active=excluded.active;
  elsif action='review.moderate' then update v1.reviews set hidden=(a->>'hidden')::boolean where id=(a->>'id')::uuid;
  else
   cid:=(a->>'catererId')::uuid;perform 1 from v1.caterers where id=cid for update;select coalesce(sum(amount-held-paid_out),0) into amt from v1.allocations where caterer_id=cid;
   if amt<=0 then raise exception 'AMOUNT_INVALID';end if;insert into v1.payouts(caterer_id,amount) values(cid,amt) returning id into ident;
   insert into v1.payout_items select ident,id,amount-held-paid_out from v1.allocations where caterer_id=cid and amount-held-paid_out>0;
   update v1.allocations set paid_out=amount-held where caterer_id=cid;insert into v1.outbox(kind,payload,dedupe) values('payout.create',jsonb_build_object('payoutId',ident),ident::text);r:=jsonb_build_object('id',ident);
  end if;
 elsif action='notification.read' then update v1.notifications set read_at=now() where user_id=u and id=(a->>'id')::uuid;
 elsif action='device.register' then insert into v1.devices(user_id,token) values(u,a->>'token') on conflict(token) do update set user_id=u;
 elsif action='invite.accept' then
  select caterer_id into cid from v1.invites where code=a->>'code' and role='staff' and used_by is null for update;if not found then raise exception 'NOT_FOUND';end if;
  insert into v1.staff values(cid,u,'staff') on conflict do nothing;update v1.invites set used_by=u where code=a->>'code';update v1.profiles set role='staff' where id=u and role='customer';
 else raise exception 'INVALID_ACTION';end if;
 insert into v1.audit(actor_id,action,details) values(u,action,jsonb_build_object('id',coalesce(r->>'id',a->>'id'),'requestId',request_id,'reason',coalesce(a->>'reason',a->>'response'),'dateBefore',d.service_date,'dateAfter',a->>'date','versionBefore',d.version,'amount',a->>'amount','status',a->>'status','catererId',coalesce(cid,p.caterer_id),'customerId',s.user_id));
 insert into v1.receipts values(u,request_id,hash,r);return r;
end $$;
create or replace function public.catera_v1_read(resource text,params jsonb default '{}') returns jsonb language plpgsql security definer set search_path='' as $$
declare u uuid:=auth.uid();result jsonb;seller_id uuid;dt date;lim int:=least(greatest(coalesce((params->>'limit')::int,50),1),100);offst int:=greatest(coalesce((params->>'offset')::int,0),0);
begin
 if resource='catalog' then
  select jsonb_build_object('items',coalesce(jsonb_agg(x.o),'[]'),'nextCursor',case when count(*)=lim then (offst+lim)::text else null end) into result from (select v1.offer(p) o from v1.packages p join v1.caterers c on c.id=p.caterer_id where p.status='published' and c.status='approved' order by case when c.areas @> array[params->>'area'] then 0 else 1 end,p.slug limit lim offset offst)x;return result;
 elsif resource='reviews' then return coalesce((select jsonb_agg(to_jsonb(r)||jsonb_build_object('customer',p.name)) from v1.reviews r join v1.profiles p on p.id=r.user_id where r.package_id=(params->>'id')::uuid and not hidden),'[]');
 end if;
 if u is null then raise exception 'UNAUTHORIZED';end if;
 if resource='actor' then return (select to_jsonb(p)||jsonb_build_object('catererId',(select caterer_id from v1.staff where user_id=u limit 1)) from v1.profiles p where p.id=u);
 elsif resource='availability' then return v1.availability(u,params);
 elsif resource='quote' then return v1.quote(u,params);
 elsif resource='checkout' then return (select to_jsonb(x) from v1.checkouts x where id=(params->>'id')::uuid and user_id=u);
 elsif resource='customer' then
  return jsonb_build_object('subscriptions',coalesce((select jsonb_agg(to_jsonb(s)||jsonb_build_object('remaining',(select count(*) from v1.delivery_days d where d.subscription_id=s.id and d.status not in('delivered','cancelled')))) from v1.subscriptions s where s.user_id=u),'[]'),'deliveries',coalesce((select jsonb_agg(v1.delivery(d) order by d.service_date) from v1.delivery_days d join v1.subscriptions s on s.id=d.subscription_id where s.user_id=u and ((params->>'deliveryId' is not null and d.id=(params->>'deliveryId')::uuid) or (params->>'deliveryId' is null and d.service_date between coalesce((params->>'from')::date,current_date-7) and coalesce((params->>'to')::date,current_date+60)))),'[]'),'addresses',coalesce((select jsonb_agg(to_jsonb(a)-'user_id') from v1.addresses a where user_id=u),'[]'),'notifications',coalesce((select jsonb_agg(to_jsonb(n)) from (select * from v1.notifications where user_id=u order by created_at desc limit 50)n),'[]'),'cases',coalesce((select jsonb_agg(to_jsonb(s)) from v1.support_cases s where user_id=u),'[]'));
 elsif resource='conversations' then
  return coalesce((select jsonb_agg(to_jsonb(c)||jsonb_build_object('caterer',k.name,'customer',p.name,'messages',coalesce((select jsonb_agg(to_jsonb(m) order by m.created_at) from (select * from v1.messages where conversation_id=c.id order by created_at desc limit 100)m),'[]'))) from v1.conversations c join v1.caterers k on k.id=c.caterer_id join v1.profiles p on p.id=c.customer_id where c.customer_id=u or v1.is_staff(u,c.caterer_id)),'[]');
 elsif resource='seller' then
  seller_id:=(params->>'id')::uuid;dt:=coalesce((params->>'date')::date,current_date);if not v1.is_staff(u,seller_id) then raise exception 'FORBIDDEN';end if;
  return jsonb_build_object('caterer',(select to_jsonb(k)||jsonb_build_object('area',k.areas) from v1.caterers k where id=seller_id),'offers',coalesce((select jsonb_agg(v1.offer(p)) from v1.packages p where caterer_id=seller_id),'[]'),'dishes',coalesce((select jsonb_agg(v1.library_dish(d) order by d.details->>'name',d.id) from v1.dishes d where d.caterer_id=seller_id),'[]'),'contentRevisions',v1.seller_content_revisions(seller_id),'datedMenus',coalesce((select jsonb_agg(to_jsonb(m)) from v1.menus m join v1.packages p on p.id=m.package_id where p.caterer_id=seller_id and m.service_date=dt),'[]'),'deliveries',coalesce((select jsonb_agg(v1.delivery(d)) from v1.delivery_days d join v1.subscriptions s on s.id=d.subscription_id join v1.packages p on p.id=s.package_id where p.caterer_id=seller_id and d.service_date=dt),'[]'),'cases',coalesce((select jsonb_agg(to_jsonb(x)) from v1.support_cases x where caterer_id=seller_id),'[]'),'customers',coalesce((select jsonb_agg(jsonb_build_object('id',p.id,'name',p.name,'source',r.source)) from v1.relationships r join v1.profiles p on p.id=r.user_id where r.caterer_id=seller_id),'[]'),'transactions',case when v1.is_staff(u,seller_id,true) then coalesce((select jsonb_agg(to_jsonb(x)) from (select ch.* from v1.checkouts ch join v1.packages p on p.id=ch.package_id where p.caterer_id=seller_id order by created_at desc limit 100)x),'[]') else '[]'::jsonb end,'staff',case when v1.is_staff(u,seller_id,true) then coalesce((select jsonb_agg(to_jsonb(s)||jsonb_build_object('name',p.name)) from v1.staff s join v1.profiles p on p.id=s.user_id where s.caterer_id=seller_id),'[]') else '[]'::jsonb end,'payouts',case when v1.is_staff(u,seller_id,true) then coalesce((select jsonb_agg(to_jsonb(p)) from v1.payouts p where caterer_id=seller_id),'[]') else '[]'::jsonb end);
 elsif resource='admin' then
  if not v1.is_admin(u) then raise exception 'FORBIDDEN';end if;
  return jsonb_build_object('caterers',coalesce((select jsonb_agg(to_jsonb(c)||jsonb_build_object('area',c.areas,'offers',coalesce((select jsonb_agg(v1.offer(pack)) from v1.packages pack where pack.caterer_id=c.id),'[]'))) from v1.caterers c),'[]'),'cases',coalesce((select jsonb_agg(to_jsonb(s)) from v1.support_cases s),'[]'),'transactions',coalesce((select jsonb_agg(to_jsonb(c)) from (select * from v1.checkouts order by created_at desc limit 100)c),'[]'),'audit',coalesce((select jsonb_agg(to_jsonb(a)) from (select * from v1.audit order by created_at desc limit 100)a),'[]'),'promotions',coalesce((select jsonb_agg(to_jsonb(p)) from v1.promotions p),'[]'),'payouts',coalesce((select jsonb_agg(to_jsonb(p)) from v1.payouts p),'[]'),'refunds',coalesce((select jsonb_agg(to_jsonb(r)) from v1.refunds r),'[]'),'reviews',coalesce((select jsonb_agg(to_jsonb(r)) from v1.reviews r),'[]'));
 end if;raise exception 'NOT_FOUND';
end $$;
revoke all on all functions in schema v1 from public,anon,authenticated;
